//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.08.27 at 01:56:16 PM CEST 
//


package ch.clustertec.estudio.schemas.prescriptionrose;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for addressComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="addressComplexType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="title" type="{http://estudio.clustertec.ch/schemas/prescription}string32" /&gt;
 *       &lt;attribute name="titleCode" type="{http://estudio.clustertec.ch/schemas/prescription}titleCode" /&gt;
 *       &lt;attribute name="lastName" type="{http://estudio.clustertec.ch/schemas/prescription}string32" /&gt;
 *       &lt;attribute name="firstName" type="{http://estudio.clustertec.ch/schemas/prescription}string32" /&gt;
 *       &lt;attribute name="additionalAddressLine" type="{http://estudio.clustertec.ch/schemas/prescription}string32" /&gt;
 *       &lt;attribute name="street" type="{http://estudio.clustertec.ch/schemas/prescription}string35" /&gt;
 *       &lt;attribute name="zipCode" type="{http://estudio.clustertec.ch/schemas/prescription}string10" /&gt;
 *       &lt;attribute name="city" type="{http://estudio.clustertec.ch/schemas/prescription}string32" /&gt;
 *       &lt;attribute name="kanton" type="{http://estudio.clustertec.ch/schemas/prescription}string2" /&gt;
 *       &lt;attribute name="country" type="{http://estudio.clustertec.ch/schemas/prescription}string2" /&gt;
 *       &lt;attribute name="phoneNrBusiness" type="{http://estudio.clustertec.ch/schemas/prescription}string20" /&gt;
 *       &lt;attribute name="phoneNrHome" type="{http://estudio.clustertec.ch/schemas/prescription}string20" /&gt;
 *       &lt;attribute name="phoneNrMobile" type="{http://estudio.clustertec.ch/schemas/prescription}string20" /&gt;
 *       &lt;attribute name="faxNr" type="{http://estudio.clustertec.ch/schemas/prescription}string20" /&gt;
 *       &lt;attribute name="email" type="{http://estudio.clustertec.ch/schemas/prescription}string100" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addressComplexType")
@XmlSeeAlso({
    PatientAddress.class,
    PrescriptorAddress.class,
    BillingAddress.class,
    DeliveryAddress.class
})
public class AddressComplexType {

    @XmlAttribute(name = "title")
    protected String title;
    @XmlAttribute(name = "titleCode")
    protected Integer titleCode;
    @XmlAttribute(name = "lastName")
    protected String lastName;
    @XmlAttribute(name = "firstName")
    protected String firstName;
    @XmlAttribute(name = "additionalAddressLine")
    protected String additionalAddressLine;
    @XmlAttribute(name = "street")
    protected String street;
    @XmlAttribute(name = "zipCode")
    protected String zipCode;
    @XmlAttribute(name = "city")
    protected String city;
    @XmlAttribute(name = "kanton")
    protected String kanton;
    @XmlAttribute(name = "country")
    protected String country;
    @XmlAttribute(name = "phoneNrBusiness")
    protected String phoneNrBusiness;
    @XmlAttribute(name = "phoneNrHome")
    protected String phoneNrHome;
    @XmlAttribute(name = "phoneNrMobile")
    protected String phoneNrMobile;
    @XmlAttribute(name = "faxNr")
    protected String faxNr;
    @XmlAttribute(name = "email")
    protected String email;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the titleCode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTitleCode() {
        return titleCode;
    }

    /**
     * Sets the value of the titleCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTitleCode(Integer value) {
        this.titleCode = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the additionalAddressLine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalAddressLine() {
        return additionalAddressLine;
    }

    /**
     * Sets the value of the additionalAddressLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalAddressLine(String value) {
        this.additionalAddressLine = value;
    }

    /**
     * Gets the value of the street property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreet() {
        return street;
    }

    /**
     * Sets the value of the street property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreet(String value) {
        this.street = value;
    }

    /**
     * Gets the value of the zipCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * Sets the value of the zipCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZipCode(String value) {
        this.zipCode = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the kanton property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKanton() {
        return kanton;
    }

    /**
     * Sets the value of the kanton property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKanton(String value) {
        this.kanton = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the phoneNrBusiness property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneNrBusiness() {
        return phoneNrBusiness;
    }

    /**
     * Sets the value of the phoneNrBusiness property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneNrBusiness(String value) {
        this.phoneNrBusiness = value;
    }

    /**
     * Gets the value of the phoneNrHome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneNrHome() {
        return phoneNrHome;
    }

    /**
     * Sets the value of the phoneNrHome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneNrHome(String value) {
        this.phoneNrHome = value;
    }

    /**
     * Gets the value of the phoneNrMobile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneNrMobile() {
        return phoneNrMobile;
    }

    /**
     * Sets the value of the phoneNrMobile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneNrMobile(String value) {
        this.phoneNrMobile = value;
    }

    /**
     * Gets the value of the faxNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaxNr() {
        return faxNr;
    }

    /**
     * Sets the value of the faxNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaxNr(String value) {
        this.faxNr = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

}
