//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.08.27 at 01:56:16 PM CEST 
//


package ch.clustertec.estudio.schemas.prescriptionrose;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="prescriptionNr1" type="{http://estudio.clustertec.ch/schemas/prescription}string7" /&gt;
 *       &lt;attribute name="positionNr1" type="{http://estudio.clustertec.ch/schemas/prescription}string10" /&gt;
 *       &lt;attribute name="pharmacode1" type="{http://estudio.clustertec.ch/schemas/prescription}string7" /&gt;
 *       &lt;attribute name="prescriptionNr2" type="{http://estudio.clustertec.ch/schemas/prescription}string7" /&gt;
 *       &lt;attribute name="positionNr2" type="{http://estudio.clustertec.ch/schemas/prescription}string10" /&gt;
 *       &lt;attribute name="pharmacode2" type="{http://estudio.clustertec.ch/schemas/prescription}string7" /&gt;
 *       &lt;attribute name="interactionState" type="{http://estudio.clustertec.ch/schemas/prescription}interactionStateType" /&gt;
 *       &lt;attribute name="interactionGrade" type="{http://estudio.clustertec.ch/schemas/prescription}interactionGradeType" /&gt;
 *       &lt;attribute name="interactionDescription" type="{http://estudio.clustertec.ch/schemas/prescription}string120" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "interaction")
public class Interaction {

    @XmlAttribute(name = "prescriptionNr1")
    protected String prescriptionNr1;
    @XmlAttribute(name = "positionNr1")
    protected String positionNr1;
    @XmlAttribute(name = "pharmacode1")
    protected String pharmacode1;
    @XmlAttribute(name = "prescriptionNr2")
    protected String prescriptionNr2;
    @XmlAttribute(name = "positionNr2")
    protected String positionNr2;
    @XmlAttribute(name = "pharmacode2")
    protected String pharmacode2;
    @XmlAttribute(name = "interactionState")
    protected String interactionState;
    @XmlAttribute(name = "interactionGrade")
    protected String interactionGrade;
    @XmlAttribute(name = "interactionDescription")
    protected String interactionDescription;

    /**
     * Gets the value of the prescriptionNr1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrescriptionNr1() {
        return prescriptionNr1;
    }

    /**
     * Sets the value of the prescriptionNr1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrescriptionNr1(String value) {
        this.prescriptionNr1 = value;
    }

    /**
     * Gets the value of the positionNr1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPositionNr1() {
        return positionNr1;
    }

    /**
     * Sets the value of the positionNr1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPositionNr1(String value) {
        this.positionNr1 = value;
    }

    /**
     * Gets the value of the pharmacode1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPharmacode1() {
        return pharmacode1;
    }

    /**
     * Sets the value of the pharmacode1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPharmacode1(String value) {
        this.pharmacode1 = value;
    }

    /**
     * Gets the value of the prescriptionNr2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrescriptionNr2() {
        return prescriptionNr2;
    }

    /**
     * Sets the value of the prescriptionNr2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrescriptionNr2(String value) {
        this.prescriptionNr2 = value;
    }

    /**
     * Gets the value of the positionNr2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPositionNr2() {
        return positionNr2;
    }

    /**
     * Sets the value of the positionNr2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPositionNr2(String value) {
        this.positionNr2 = value;
    }

    /**
     * Gets the value of the pharmacode2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPharmacode2() {
        return pharmacode2;
    }

    /**
     * Sets the value of the pharmacode2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPharmacode2(String value) {
        this.pharmacode2 = value;
    }

    /**
     * Gets the value of the interactionState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInteractionState() {
        return interactionState;
    }

    /**
     * Sets the value of the interactionState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInteractionState(String value) {
        this.interactionState = value;
    }

    /**
     * Gets the value of the interactionGrade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInteractionGrade() {
        return interactionGrade;
    }

    /**
     * Sets the value of the interactionGrade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInteractionGrade(String value) {
        this.interactionGrade = value;
    }

    /**
     * Gets the value of the interactionDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInteractionDescription() {
        return interactionDescription;
    }

    /**
     * Sets the value of the interactionDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInteractionDescription(String value) {
        this.interactionDescription = value;
    }

}
