//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.08.27 at 01:56:16 PM CEST 
//


package ch.clustertec.estudio.schemas.prescriptionrose;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="prescriptionNr" type="{http://estudio.clustertec.ch/schemas/prescription}string7" /&gt;
 *       &lt;attribute name="positionNr" type="{http://estudio.clustertec.ch/schemas/prescription}string10" /&gt;
 *       &lt;attribute name="pharmacode" type="{http://estudio.clustertec.ch/schemas/prescription}string7" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "interactionProduct")
public class InteractionProduct {

    @XmlAttribute(name = "prescriptionNr")
    protected String prescriptionNr;
    @XmlAttribute(name = "positionNr")
    protected String positionNr;
    @XmlAttribute(name = "pharmacode")
    protected String pharmacode;

    /**
     * Gets the value of the prescriptionNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrescriptionNr() {
        return prescriptionNr;
    }

    /**
     * Sets the value of the prescriptionNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrescriptionNr(String value) {
        this.prescriptionNr = value;
    }

    /**
     * Gets the value of the positionNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPositionNr() {
        return positionNr;
    }

    /**
     * Sets the value of the positionNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPositionNr(String value) {
        this.positionNr = value;
    }

    /**
     * Gets the value of the pharmacode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPharmacode() {
        return pharmacode;
    }

    /**
     * Sets the value of the pharmacode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPharmacode(String value) {
        this.pharmacode = value;
    }

}
