//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.08.27 at 01:56:16 PM CEST 
//


package ch.clustertec.estudio.schemas.prescriptionrose;

import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ch.clustertec.estudio.schemas.prescriptionrose package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Weekday_QNAME = new QName("http://estudio.clustertec.ch/schemas/prescription", "weekday");
    private final static QName _IntakeTime_QNAME = new QName("http://estudio.clustertec.ch/schemas/prescription", "intakeTime");
    private final static QName _AmountOfTablets_QNAME = new QName("http://estudio.clustertec.ch/schemas/prescription", "amountOfTablets");
    private final static QName _TabletFraction_QNAME = new QName("http://estudio.clustertec.ch/schemas/prescription", "tabletFraction");
    private final static QName _IndicationCode_QNAME = new QName("http://estudio.clustertec.ch/schemas/prescription", "indicationCode");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ch.clustertec.estudio.schemas.prescriptionrose
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeliveryAddress }
     * 
     */
    public DeliveryAddress createDeliveryAddress() {
        return new DeliveryAddress();
    }

    /**
     * Create an instance of {@link AddressComplexType }
     * 
     */
    public AddressComplexType createAddressComplexType() {
        return new AddressComplexType();
    }

    /**
     * Create an instance of {@link BillingAddress }
     * 
     */
    public BillingAddress createBillingAddress() {
        return new BillingAddress();
    }

    /**
     * Create an instance of {@link PrescriptorAddress }
     * 
     */
    public PrescriptorAddress createPrescriptorAddress() {
        return new PrescriptorAddress();
    }

    /**
     * Create an instance of {@link PatientAddress }
     * 
     */
    public PatientAddress createPatientAddress() {
        return new PatientAddress();
    }

    /**
     * Create an instance of {@link Posology }
     * 
     */
    public Posology createPosology() {
        return new Posology();
    }

    /**
     * Create an instance of {@link Dailymed }
     * 
     */
    public Dailymed createDailymed() {
        return new Dailymed();
    }

    /**
     * Create an instance of {@link DailymedPosition }
     * 
     */
    public DailymedPosition createDailymedPosition() {
        return new DailymedPosition();
    }

    /**
     * Create an instance of {@link DailymedDosage }
     * 
     */
    public DailymedDosage createDailymedDosage() {
        return new DailymedDosage();
    }

    /**
     * Create an instance of {@link Insurance }
     * 
     */
    public Insurance createInsurance() {
        return new Insurance();
    }

    /**
     * Create an instance of {@link Product }
     * 
     */
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link InteractionProduct }
     * 
     */
    public InteractionProduct createInteractionProduct() {
        return new InteractionProduct();
    }

    /**
     * Create an instance of {@link Interaction }
     * 
     */
    public Interaction createInteraction() {
        return new Interaction();
    }

    /**
     * Create an instance of {@link RepetitionPos }
     * 
     */
    public RepetitionPos createRepetitionPos() {
        return new RepetitionPos();
    }

    /**
     * Create an instance of {@link Prescription }
     * 
     */
    public Prescription createPrescription() {
        return new Prescription();
    }

    /**
     * Create an instance of {@link PrescriptionResponse }
     * 
     */
    public PrescriptionResponse createPrescriptionResponse() {
        return new PrescriptionResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WeekdayType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link WeekdayType }{@code >}
     */
    @XmlElementDecl(namespace = "http://estudio.clustertec.ch/schemas/prescription", name = "weekday")
    public JAXBElement<WeekdayType> createWeekday(WeekdayType value) {
        return new JAXBElement<WeekdayType>(_Weekday_QNAME, WeekdayType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://estudio.clustertec.ch/schemas/prescription", name = "intakeTime")
    public JAXBElement<XMLGregorianCalendar> createIntakeTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_IntakeTime_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://estudio.clustertec.ch/schemas/prescription", name = "amountOfTablets")
    public JAXBElement<Integer> createAmountOfTablets(Integer value) {
        return new JAXBElement<Integer>(_AmountOfTablets_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TabletFractionType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TabletFractionType }{@code >}
     */
    @XmlElementDecl(namespace = "http://estudio.clustertec.ch/schemas/prescription", name = "tabletFraction")
    public JAXBElement<TabletFractionType> createTabletFraction(TabletFractionType value) {
        return new JAXBElement<TabletFractionType>(_TabletFraction_QNAME, TabletFractionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://estudio.clustertec.ch/schemas/prescription", name = "indicationCode")
    public JAXBElement<String> createIndicationCode(String value) {
        return new JAXBElement<String>(_IndicationCode_QNAME, String.class, null, value);
    }

}
