//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.08.27 at 01:56:16 PM CEST 
//


package ch.clustertec.estudio.schemas.prescriptionrose;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="qtyMorning" type="{http://estudio.clustertec.ch/schemas/prescription}string6" /&gt;
 *       &lt;attribute name="qtyMidday" type="{http://estudio.clustertec.ch/schemas/prescription}string6" /&gt;
 *       &lt;attribute name="qtyEvening" type="{http://estudio.clustertec.ch/schemas/prescription}string6" /&gt;
 *       &lt;attribute name="qtyNight" type="{http://estudio.clustertec.ch/schemas/prescription}string6" /&gt;
 *       &lt;attribute name="posologyText" type="{http://estudio.clustertec.ch/schemas/prescription}string70" /&gt;
 *       &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "posology")
public class Posology {

    @XmlAttribute(name = "qtyMorning")
    protected String qtyMorning;
    @XmlAttribute(name = "qtyMidday")
    protected String qtyMidday;
    @XmlAttribute(name = "qtyEvening")
    protected String qtyEvening;
    @XmlAttribute(name = "qtyNight")
    protected String qtyNight;
    @XmlAttribute(name = "posologyText")
    protected String posologyText;
    @XmlAttribute(name = "label")
    protected Boolean label;

    /**
     * Gets the value of the qtyMorning property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQtyMorning() {
        return qtyMorning;
    }

    /**
     * Sets the value of the qtyMorning property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQtyMorning(String value) {
        this.qtyMorning = value;
    }

    /**
     * Gets the value of the qtyMidday property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQtyMidday() {
        return qtyMidday;
    }

    /**
     * Sets the value of the qtyMidday property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQtyMidday(String value) {
        this.qtyMidday = value;
    }

    /**
     * Gets the value of the qtyEvening property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQtyEvening() {
        return qtyEvening;
    }

    /**
     * Sets the value of the qtyEvening property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQtyEvening(String value) {
        this.qtyEvening = value;
    }

    /**
     * Gets the value of the qtyNight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQtyNight() {
        return qtyNight;
    }

    /**
     * Sets the value of the qtyNight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQtyNight(String value) {
        this.qtyNight = value;
    }

    /**
     * Gets the value of the posologyText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPosologyText() {
        return posologyText;
    }

    /**
     * Sets the value of the posologyText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPosologyText(String value) {
        this.posologyText = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLabel(Boolean value) {
        this.label = value;
    }

}
