//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.08.27 at 01:56:16 PM CEST 
//


package ch.clustertec.estudio.schemas.prescriptionrose;

import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://estudio.clustertec.ch/schemas/prescription}dailymed" minOccurs="0"/&gt;
 *         &lt;element ref="{http://estudio.clustertec.ch/schemas/prescription}prescriptorAddress"/&gt;
 *         &lt;element ref="{http://estudio.clustertec.ch/schemas/prescription}patientAddress"/&gt;
 *         &lt;element ref="{http://estudio.clustertec.ch/schemas/prescription}deliveryAddress" minOccurs="0"/&gt;
 *         &lt;element ref="{http://estudio.clustertec.ch/schemas/prescription}billingAddress" minOccurs="0"/&gt;
 *         &lt;element ref="{http://estudio.clustertec.ch/schemas/prescription}product" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="issueDate" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *       &lt;attribute name="validity" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *       &lt;attribute name="clustertecPrescriptionNr" type="{http://estudio.clustertec.ch/schemas/prescription}string8" /&gt;
 *       &lt;attribute name="prescriptorPrescriptionNr" type="{http://estudio.clustertec.ch/schemas/prescription}string9" /&gt;
 *       &lt;attribute name="deliveryType" type="{http://estudio.clustertec.ch/schemas/prescription}deliveryType" /&gt;
 *       &lt;attribute name="comment" type="{http://estudio.clustertec.ch/schemas/prescription}string2000" /&gt;
 *       &lt;attribute name="prescriptionCategory" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="user" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="password" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="prescriptionNr" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ignoreInteractions" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="interactionsWithOldPres" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dailymed",
    "prescriptorAddress",
    "patientAddress",
    "deliveryAddress",
    "billingAddress",
    "product"
})
@XmlRootElement(name = "prescription")
public class Prescription {

    protected Dailymed dailymed;
    @XmlElement(required = true)
    protected PrescriptorAddress prescriptorAddress;
    @XmlElement(required = true)
    protected PatientAddress patientAddress;
    protected DeliveryAddress deliveryAddress;
    protected BillingAddress billingAddress;
    @XmlElement(required = true)
    protected List<Product> product;
    @XmlAttribute(name = "issueDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar issueDate;
    @XmlAttribute(name = "validity")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar validity;
    @XmlAttribute(name = "clustertecPrescriptionNr")
    protected String clustertecPrescriptionNr;
    @XmlAttribute(name = "prescriptorPrescriptionNr")
    protected String prescriptorPrescriptionNr;
    @XmlAttribute(name = "deliveryType")
    protected Integer deliveryType;
    @XmlAttribute(name = "comment")
    protected String comment;
    @XmlAttribute(name = "prescriptionCategory")
    protected String prescriptionCategory;
    @XmlAttribute(name = "user")
    protected String user;
    @XmlAttribute(name = "password")
    protected String password;
    @XmlAttribute(name = "prescriptionNr")
    protected String prescriptionNr;
    @XmlAttribute(name = "ignoreInteractions")
    protected String ignoreInteractions;
    @XmlAttribute(name = "interactionsWithOldPres")
    protected String interactionsWithOldPres;

    /**
     * Gets the value of the dailymed property.
     * 
     * @return
     *     possible object is
     *     {@link Dailymed }
     *     
     */
    public Dailymed getDailymed() {
        return dailymed;
    }

    /**
     * Sets the value of the dailymed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dailymed }
     *     
     */
    public void setDailymed(Dailymed value) {
        this.dailymed = value;
    }

    /**
     * Gets the value of the prescriptorAddress property.
     * 
     * @return
     *     possible object is
     *     {@link PrescriptorAddress }
     *     
     */
    public PrescriptorAddress getPrescriptorAddress() {
        return prescriptorAddress;
    }

    /**
     * Sets the value of the prescriptorAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrescriptorAddress }
     *     
     */
    public void setPrescriptorAddress(PrescriptorAddress value) {
        this.prescriptorAddress = value;
    }

    /**
     * Gets the value of the patientAddress property.
     * 
     * @return
     *     possible object is
     *     {@link PatientAddress }
     *     
     */
    public PatientAddress getPatientAddress() {
        return patientAddress;
    }

    /**
     * Sets the value of the patientAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link PatientAddress }
     *     
     */
    public void setPatientAddress(PatientAddress value) {
        this.patientAddress = value;
    }

    /**
     * Gets the value of the deliveryAddress property.
     * 
     * @return
     *     possible object is
     *     {@link DeliveryAddress }
     *     
     */
    public DeliveryAddress getDeliveryAddress() {
        return deliveryAddress;
    }

    /**
     * Sets the value of the deliveryAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliveryAddress }
     *     
     */
    public void setDeliveryAddress(DeliveryAddress value) {
        this.deliveryAddress = value;
    }

    /**
     * Gets the value of the billingAddress property.
     * 
     * @return
     *     possible object is
     *     {@link BillingAddress }
     *     
     */
    public BillingAddress getBillingAddress() {
        return billingAddress;
    }

    /**
     * Sets the value of the billingAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillingAddress }
     *     
     */
    public void setBillingAddress(BillingAddress value) {
        this.billingAddress = value;
    }

    /**
     * Gets the value of the product property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the product property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProduct().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Product }
     * 
     * 
     */
    public List<Product> getProduct() {
        if (product == null) {
            product = new ArrayList<Product>();
        }
        return this.product;
    }

    /**
     * Gets the value of the issueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getIssueDate() {
        return issueDate;
    }

    /**
     * Sets the value of the issueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setIssueDate(XMLGregorianCalendar value) {
        this.issueDate = value;
    }

    /**
     * Gets the value of the validity property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidity() {
        return validity;
    }

    /**
     * Sets the value of the validity property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidity(XMLGregorianCalendar value) {
        this.validity = value;
    }

    /**
     * Gets the value of the clustertecPrescriptionNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClustertecPrescriptionNr() {
        return clustertecPrescriptionNr;
    }

    /**
     * Sets the value of the clustertecPrescriptionNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClustertecPrescriptionNr(String value) {
        this.clustertecPrescriptionNr = value;
    }

    /**
     * Gets the value of the prescriptorPrescriptionNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrescriptorPrescriptionNr() {
        return prescriptorPrescriptionNr;
    }

    /**
     * Sets the value of the prescriptorPrescriptionNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrescriptorPrescriptionNr(String value) {
        this.prescriptorPrescriptionNr = value;
    }

    /**
     * Gets the value of the deliveryType property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDeliveryType() {
        return deliveryType;
    }

    /**
     * Sets the value of the deliveryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDeliveryType(Integer value) {
        this.deliveryType = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the prescriptionCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrescriptionCategory() {
        return prescriptionCategory;
    }

    /**
     * Sets the value of the prescriptionCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrescriptionCategory(String value) {
        this.prescriptionCategory = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUser(String value) {
        this.user = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the prescriptionNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrescriptionNr() {
        return prescriptionNr;
    }

    /**
     * Sets the value of the prescriptionNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrescriptionNr(String value) {
        this.prescriptionNr = value;
    }

    /**
     * Gets the value of the ignoreInteractions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIgnoreInteractions() {
        return ignoreInteractions;
    }

    /**
     * Sets the value of the ignoreInteractions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIgnoreInteractions(String value) {
        this.ignoreInteractions = value;
    }

    /**
     * Gets the value of the interactionsWithOldPres property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInteractionsWithOldPres() {
        return interactionsWithOldPres;
    }

    /**
     * Sets the value of the interactionsWithOldPres property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInteractionsWithOldPres(String value) {
        this.interactionsWithOldPres = value;
    }

}
