
package ch.pharmedsolutions.www.apothekenservice;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.6-1b01 Generated
 * source version: 2.2
 *
 */
@WebServiceClient(name = "ApothekenService", targetNamespace = "https://www.pharmedsolutions.ch/ApothekenService", wsdlLocation = "https://www.pharmedsolutions.ch/ApothekenService/wsdl")
public class ApothekenService extends Service {

	private final static URL APOTHEKENSERVICE_WSDL_LOCATION;
	private final static WebServiceException APOTHEKENSERVICE_EXCEPTION;
	private final static QName APOTHEKENSERVICE_QNAME = new QName("https://www.pharmedsolutions.ch/ApothekenService",
			"ApothekenService");

	static {
		URL url = null;
		WebServiceException e = null;
		try {
			url = new URL("https://www.pharmedsolutions.ch/ApothekenService/wsdl");
		} catch (MalformedURLException ex) {
			e = new WebServiceException(ex);
		}
		APOTHEKENSERVICE_WSDL_LOCATION = url;
		APOTHEKENSERVICE_EXCEPTION = e;
	}

	public ApothekenService() {
		super(__getWsdlLocation(), APOTHEKENSERVICE_QNAME);
	}

	public ApothekenService(WebServiceFeature... features) {
		super(__getWsdlLocation(), APOTHEKENSERVICE_QNAME, features);
	}

	public ApothekenService(URL wsdlLocation) {
		super(wsdlLocation, APOTHEKENSERVICE_QNAME);
	}

	public ApothekenService(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, APOTHEKENSERVICE_QNAME, features);
	}

	public ApothekenService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ApothekenService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	/**
	 *
	 * @return returns ApothekenPortType
	 */
	@WebEndpoint(name = "ApothekenPort")
	public ApothekenPortType getApothekenPort() {
		return super.getPort(new QName("https://www.pharmedsolutions.ch/ApothekenService", "ApothekenPort"),
				ApothekenPortType.class);
	}

	/**
	 *
	 * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *                 on the proxy. Supported features not in the
	 *                 <code>features</code> parameter will have their default
	 *                 values.
	 * @return returns ApothekenPortType
	 */
	@WebEndpoint(name = "ApothekenPort")
	public ApothekenPortType getApothekenPort(WebServiceFeature... features) {
		return super.getPort(new QName("https://www.pharmedsolutions.ch/ApothekenService", "ApothekenPort"),
				ApothekenPortType.class, features);
	}

	private static URL __getWsdlLocation() {
		if (APOTHEKENSERVICE_EXCEPTION != null) {
			throw APOTHEKENSERVICE_EXCEPTION;
		}
		return APOTHEKENSERVICE_WSDL_LOCATION;
	}

}
