//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.18 at 01:35:39 PM CET 
//

package ch.fd.invoice400.request;

import java.math.BigInteger;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for dataValidatorType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dataValidatorType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.xmlData.ch/xmlInvoice/XSD>stringType1_350">
 *       &lt;attribute name="focus" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="tarmed"/>
 *             &lt;enumeration value="cantonal"/>
 *             &lt;enumeration value="lab"/>
 *             &lt;enumeration value="unclassified"/>
 *             &lt;enumeration value="drug"/>
 *             &lt;enumeration value="migel"/>
 *             &lt;enumeration value="physio"/>
 *             &lt;enumeration value="other"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="version_software" use="required" type="{http://www.xmlData.ch/xmlInvoice/XSD}versionType" />
 *       &lt;attribute name="version_db" use="required" type="{http://www.xmlData.ch/xmlInvoice/XSD}versionType" />
 *       &lt;attribute name="id" default="0">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *             &lt;minInclusive value="0"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dataValidatorType", propOrder = {
	"value"
})
public class DataValidatorType {
	
	@XmlValue
	protected String value;
	@XmlAttribute(name = "focus", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String focus;
	@XmlAttribute(name = "version_software", required = true)
	protected BigInteger versionSoftware;
	@XmlAttribute(name = "version_db", required = true)
	protected BigInteger versionDb;
	@XmlAttribute(name = "id")
	protected BigInteger id;
	
	/**
	 * Gets the value of the value property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getValue(){
		return value;
	}
	
	/**
	 * Sets the value of the value property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setValue(String value){
		this.value = value;
	}
	
	/**
	 * Gets the value of the focus property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFocus(){
		return focus;
	}
	
	/**
	 * Sets the value of the focus property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFocus(String value){
		this.focus = value;
	}
	
	/**
	 * Gets the value of the versionSoftware property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getVersionSoftware(){
		return versionSoftware;
	}
	
	/**
	 * Sets the value of the versionSoftware property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setVersionSoftware(BigInteger value){
		this.versionSoftware = value;
	}
	
	/**
	 * Gets the value of the versionDb property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getVersionDb(){
		return versionDb;
	}
	
	/**
	 * Sets the value of the versionDb property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setVersionDb(BigInteger value){
		this.versionDb = value;
	}
	
	/**
	 * Gets the value of the id property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getId(){
		if (id == null) {
			return new BigInteger("0");
		} else {
			return id;
		}
	}
	
	/**
	 * Sets the value of the id property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setId(BigInteger value){
		this.id = value;
	}
	
}
