//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.18 at 01:35:39 PM CET 
//

package ch.fd.invoice400.request;

import javax.xml.datatype.XMLGregorianCalendar;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for demandType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="demandType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="tc_demand_id" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="tc_token" use="required" type="{http://www.xmlData.ch/xmlInvoice/XSD}stringType1_100" />
 *       &lt;attribute name="insurance_demand_date" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="insurance_demand_id" type="{http://www.xmlData.ch/xmlInvoice/XSD}stringType1_35" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "demandType")
public class DemandType {
	
	@XmlAttribute(name = "tc_demand_id", required = true)
	protected long tcDemandId;
	@XmlAttribute(name = "tc_token", required = true)
	protected String tcToken;
	@XmlAttribute(name = "insurance_demand_date", required = true)
	@XmlSchemaType(name = "dateTime")
	protected XMLGregorianCalendar insuranceDemandDate;
	@XmlAttribute(name = "insurance_demand_id")
	protected String insuranceDemandId;
	
	/**
	 * Gets the value of the tcDemandId property.
	 * 
	 */
	public long getTcDemandId(){
		return tcDemandId;
	}
	
	/**
	 * Sets the value of the tcDemandId property.
	 * 
	 */
	public void setTcDemandId(long value){
		this.tcDemandId = value;
	}
	
	/**
	 * Gets the value of the tcToken property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTcToken(){
		return tcToken;
	}
	
	/**
	 * Sets the value of the tcToken property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTcToken(String value){
		this.tcToken = value;
	}
	
	/**
	 * Gets the value of the insuranceDemandDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getInsuranceDemandDate(){
		return insuranceDemandDate;
	}
	
	/**
	 * Sets the value of the insuranceDemandDate property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setInsuranceDemandDate(XMLGregorianCalendar value){
		this.insuranceDemandDate = value;
	}
	
	/**
	 * Gets the value of the insuranceDemandId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getInsuranceDemandId(){
		return insuranceDemandId;
	}
	
	/**
	 * Sets the value of the insuranceDemandId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setInsuranceDemandId(String value){
		this.insuranceDemandId = value;
	}
	
}
