//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.18 at 01:35:39 PM CET 
//

package ch.fd.invoice400.request;

import javax.xml.datatype.Duration;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for garantType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="garantType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="biller" type="{http://www.xmlData.ch/xmlInvoice/XSD}billerAddressType"/>
 *         &lt;element name="provider" type="{http://www.xmlData.ch/xmlInvoice/XSD}providerAddressType"/>
 *         &lt;element name="insurance" type="{http://www.xmlData.ch/xmlInvoice/XSD}insuranceAddressType" minOccurs="0"/>
 *         &lt;element name="patient" type="{http://www.xmlData.ch/xmlInvoice/XSD}patientAddressType"/>
 *         &lt;element name="guarantor" type="{http://www.xmlData.ch/xmlInvoice/XSD}guarantorAddressType"/>
 *         &lt;element name="referrer" type="{http://www.xmlData.ch/xmlInvoice/XSD}referrerAddressType" minOccurs="0"/>
 *         &lt;element name="demand" type="{http://www.xmlData.ch/xmlInvoice/XSD}demandType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="payment_periode" type="{http://www.w3.org/2001/XMLSchema}duration" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "garantType", propOrder = {
	"biller", "provider", "insurance", "patient", "guarantor", "referrer", "demand"
})
public class GarantType {
	
	@XmlElement(required = true)
	protected BillerAddressType biller;
	@XmlElement(required = true)
	protected ProviderAddressType provider;
	protected InsuranceAddressType insurance;
	@XmlElement(required = true)
	protected PatientAddressType patient;
	@XmlElement(required = true)
	protected GuarantorAddressType guarantor;
	protected ReferrerAddressType referrer;
	protected DemandType demand;
	@XmlAttribute(name = "payment_periode")
	protected Duration paymentPeriode;
	
	/**
	 * Gets the value of the biller property.
	 * 
	 * @return possible object is {@link BillerAddressType }
	 * 
	 */
	public BillerAddressType getBiller(){
		return biller;
	}
	
	/**
	 * Sets the value of the biller property.
	 * 
	 * @param value
	 *            allowed object is {@link BillerAddressType }
	 * 
	 */
	public void setBiller(BillerAddressType value){
		this.biller = value;
	}
	
	/**
	 * Gets the value of the provider property.
	 * 
	 * @return possible object is {@link ProviderAddressType }
	 * 
	 */
	public ProviderAddressType getProvider(){
		return provider;
	}
	
	/**
	 * Sets the value of the provider property.
	 * 
	 * @param value
	 *            allowed object is {@link ProviderAddressType }
	 * 
	 */
	public void setProvider(ProviderAddressType value){
		this.provider = value;
	}
	
	/**
	 * Gets the value of the insurance property.
	 * 
	 * @return possible object is {@link InsuranceAddressType }
	 * 
	 */
	public InsuranceAddressType getInsurance(){
		return insurance;
	}
	
	/**
	 * Sets the value of the insurance property.
	 * 
	 * @param value
	 *            allowed object is {@link InsuranceAddressType }
	 * 
	 */
	public void setInsurance(InsuranceAddressType value){
		this.insurance = value;
	}
	
	/**
	 * Gets the value of the patient property.
	 * 
	 * @return possible object is {@link PatientAddressType }
	 * 
	 */
	public PatientAddressType getPatient(){
		return patient;
	}
	
	/**
	 * Sets the value of the patient property.
	 * 
	 * @param value
	 *            allowed object is {@link PatientAddressType }
	 * 
	 */
	public void setPatient(PatientAddressType value){
		this.patient = value;
	}
	
	/**
	 * Gets the value of the guarantor property.
	 * 
	 * @return possible object is {@link GuarantorAddressType }
	 * 
	 */
	public GuarantorAddressType getGuarantor(){
		return guarantor;
	}
	
	/**
	 * Sets the value of the guarantor property.
	 * 
	 * @param value
	 *            allowed object is {@link GuarantorAddressType }
	 * 
	 */
	public void setGuarantor(GuarantorAddressType value){
		this.guarantor = value;
	}
	
	/**
	 * Gets the value of the referrer property.
	 * 
	 * @return possible object is {@link ReferrerAddressType }
	 * 
	 */
	public ReferrerAddressType getReferrer(){
		return referrer;
	}
	
	/**
	 * Sets the value of the referrer property.
	 * 
	 * @param value
	 *            allowed object is {@link ReferrerAddressType }
	 * 
	 */
	public void setReferrer(ReferrerAddressType value){
		this.referrer = value;
	}
	
	/**
	 * Gets the value of the demand property.
	 * 
	 * @return possible object is {@link DemandType }
	 * 
	 */
	public DemandType getDemand(){
		return demand;
	}
	
	/**
	 * Sets the value of the demand property.
	 * 
	 * @param value
	 *            allowed object is {@link DemandType }
	 * 
	 */
	public void setDemand(DemandType value){
		this.demand = value;
	}
	
	/**
	 * Gets the value of the paymentPeriode property.
	 * 
	 * @return possible object is {@link Duration }
	 * 
	 */
	public Duration getPaymentPeriode(){
		return paymentPeriode;
	}
	
	/**
	 * Sets the value of the paymentPeriode property.
	 * 
	 * @param value
	 *            allowed object is {@link Duration }
	 * 
	 */
	public void setPaymentPeriode(Duration value){
		this.paymentPeriode = value;
	}
	
}
