//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.18 at 01:35:39 PM CET 
//

package ch.fd.invoice400.request;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for headerType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="headerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sender" type="{http://www.xmlData.ch/xmlInvoice/XSD}headerPartyType"/>
 *         &lt;element name="intermediate" type="{http://www.xmlData.ch/xmlInvoice/XSD}headerPartyType"/>
 *         &lt;element name="recipient" type="{http://www.xmlData.ch/xmlInvoice/XSD}xtendHeaderPartyType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "headerType", propOrder = {
	"sender", "intermediate", "recipient"
})
public class HeaderType {
	
	@XmlElement(required = true)
	protected HeaderPartyType sender;
	@XmlElement(required = true)
	protected HeaderPartyType intermediate;
	@XmlElement(required = true)
	protected XtendHeaderPartyType recipient;
	
	/**
	 * Gets the value of the sender property.
	 * 
	 * @return possible object is {@link HeaderPartyType }
	 * 
	 */
	public HeaderPartyType getSender(){
		return sender;
	}
	
	/**
	 * Sets the value of the sender property.
	 * 
	 * @param value
	 *            allowed object is {@link HeaderPartyType }
	 * 
	 */
	public void setSender(HeaderPartyType value){
		this.sender = value;
	}
	
	/**
	 * Gets the value of the intermediate property.
	 * 
	 * @return possible object is {@link HeaderPartyType }
	 * 
	 */
	public HeaderPartyType getIntermediate(){
		return intermediate;
	}
	
	/**
	 * Sets the value of the intermediate property.
	 * 
	 * @param value
	 *            allowed object is {@link HeaderPartyType }
	 * 
	 */
	public void setIntermediate(HeaderPartyType value){
		this.intermediate = value;
	}
	
	/**
	 * Gets the value of the recipient property.
	 * 
	 * @return possible object is {@link XtendHeaderPartyType }
	 * 
	 */
	public XtendHeaderPartyType getRecipient(){
		return recipient;
	}
	
	/**
	 * Sets the value of the recipient property.
	 * 
	 * @param value
	 *            allowed object is {@link XtendHeaderPartyType }
	 * 
	 */
	public void setRecipient(XtendHeaderPartyType value){
		this.recipient = value;
	}
	
}
