//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.18 at 01:35:39 PM CET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.xmlData.ch/xmlInvoice/XSD", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ch.fd.invoice400.request;

