//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.18 at 01:35:39 PM CET 
//

package ch.fd.invoice400.request;

import javax.xml.datatype.XMLGregorianCalendar;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for patientAddressType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="patientAddressType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="person" type="{http://www.xmlData.ch/xmlInvoice/XSD}patientPersonType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="gender" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="male"/>
 *             &lt;enumeration value="female"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="birthdate" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="unique_id" type="{http://www.xmlData.ch/xmlInvoice/XSD}ssn13PartyType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "patientAddressType", propOrder = {
	"person"
})
public class PatientAddressType {
	
	@XmlElement(required = true)
	protected PatientPersonType person;
	@XmlAttribute(name = "gender", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String gender;
	@XmlAttribute(name = "birthdate", required = true)
	@XmlSchemaType(name = "dateTime")
	protected XMLGregorianCalendar birthdate;
	@XmlAttribute(name = "unique_id")
	protected String uniqueId;
	
	/**
	 * Gets the value of the person property.
	 * 
	 * @return possible object is {@link PatientPersonType }
	 * 
	 */
	public PatientPersonType getPerson(){
		return person;
	}
	
	/**
	 * Sets the value of the person property.
	 * 
	 * @param value
	 *            allowed object is {@link PatientPersonType }
	 * 
	 */
	public void setPerson(PatientPersonType value){
		this.person = value;
	}
	
	/**
	 * Gets the value of the gender property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getGender(){
		return gender;
	}
	
	/**
	 * Sets the value of the gender property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setGender(String value){
		this.gender = value;
	}
	
	/**
	 * Gets the value of the birthdate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getBirthdate(){
		return birthdate;
	}
	
	/**
	 * Sets the value of the birthdate property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setBirthdate(XMLGregorianCalendar value){
		this.birthdate = value;
	}
	
	/**
	 * Gets the value of the uniqueId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUniqueId(){
		return uniqueId;
	}
	
	/**
	 * Sets the value of the uniqueId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setUniqueId(String value){
		this.uniqueId = value;
	}
	
}
