//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.18 at 01:35:39 PM CET 
//

package ch.fd.invoice400.request;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for requestType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="requestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="header" type="{http://www.xmlData.ch/xmlInvoice/XSD}headerType"/>
 *         &lt;element name="prolog" type="{http://www.xmlData.ch/xmlInvoice/XSD}prologType"/>
 *         &lt;element name="invoice" type="{http://www.xmlData.ch/xmlInvoice/XSD}invoiceType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="role" default="production">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="production"/>
 *             &lt;enumeration value="test"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "requestType", propOrder = {
	"header", "prolog", "invoice"
})
@XmlRootElement(name = "request")
public class RequestType {
	
	@XmlElement(required = true)
	protected HeaderType header;
	@XmlElement(required = true)
	protected PrologType prolog;
	@XmlElement(required = true)
	protected InvoiceType invoice;
	@XmlAttribute(name = "role")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String role;
	
	/**
	 * Gets the value of the header property.
	 * 
	 * @return possible object is {@link HeaderType }
	 * 
	 */
	public HeaderType getHeader(){
		return header;
	}
	
	/**
	 * Sets the value of the header property.
	 * 
	 * @param value
	 *            allowed object is {@link HeaderType }
	 * 
	 */
	public void setHeader(HeaderType value){
		this.header = value;
	}
	
	/**
	 * Gets the value of the prolog property.
	 * 
	 * @return possible object is {@link PrologType }
	 * 
	 */
	public PrologType getProlog(){
		return prolog;
	}
	
	/**
	 * Sets the value of the prolog property.
	 * 
	 * @param value
	 *            allowed object is {@link PrologType }
	 * 
	 */
	public void setProlog(PrologType value){
		this.prolog = value;
	}
	
	/**
	 * Gets the value of the invoice property.
	 * 
	 * @return possible object is {@link InvoiceType }
	 * 
	 */
	public InvoiceType getInvoice(){
		return invoice;
	}
	
	/**
	 * Sets the value of the invoice property.
	 * 
	 * @param value
	 *            allowed object is {@link InvoiceType }
	 * 
	 */
	public void setInvoice(InvoiceType value){
		this.invoice = value;
	}
	
	/**
	 * Gets the value of the role property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRole(){
		if (role == null) {
			return "production";
		} else {
			return role;
		}
	}
	
	/**
	 * Sets the value of the role property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRole(String value){
		this.role = value;
	}
	
}
