//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.18 at 01:35:39 PM CET 
//

package ch.fd.invoice400.request;

import java.util.ArrayList;
import java.util.List;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElements;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for servicesType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="servicesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="record_tarmed" type="{http://www.xmlData.ch/xmlInvoice/XSD}recordTarmedType"/>
 *         &lt;element name="record_cantonal" type="{http://www.xmlData.ch/xmlInvoice/XSD}recordCantonalType"/>
 *         &lt;element name="record_unclassified" type="{http://www.xmlData.ch/xmlInvoice/XSD}recordUnclassifiedType"/>
 *         &lt;element name="record_lab" type="{http://www.xmlData.ch/xmlInvoice/XSD}recordLabType"/>
 *         &lt;element name="record_migel" type="{http://www.xmlData.ch/xmlInvoice/XSD}recordMigelType"/>
 *         &lt;element name="record_physio" type="{http://www.xmlData.ch/xmlInvoice/XSD}recordPhysioType"/>
 *         &lt;element name="record_drug" type="{http://www.xmlData.ch/xmlInvoice/XSD}recordDrugType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "servicesType", propOrder = {
	"recordTarmedOrRecordCantonalOrRecordUnclassified"
})
public class ServicesType {
	
	@XmlElements({
		@XmlElement(name = "record_tarmed", type = RecordTarmedType.class),
		@XmlElement(name = "record_cantonal", type = RecordCantonalType.class),
		@XmlElement(name = "record_unclassified", type = RecordUnclassifiedType.class),
		@XmlElement(name = "record_lab", type = RecordLabType.class),
		@XmlElement(name = "record_migel", type = RecordMigelType.class),
		@XmlElement(name = "record_physio", type = RecordPhysioType.class),
		@XmlElement(name = "record_drug", type = RecordDrugType.class)
	})
	protected List<Object> recordTarmedOrRecordCantonalOrRecordUnclassified;
	
	/**
	 * Gets the value of the recordTarmedOrRecordCantonalOrRecordUnclassified property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any
	 * modification you make to the returned list will be present inside the JAXB object. This is
	 * why there is not a <CODE>set</CODE> method for the
	 * recordTarmedOrRecordCantonalOrRecordUnclassified property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getRecordTarmedOrRecordCantonalOrRecordUnclassified().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link RecordTarmedType }
	 * {@link RecordCantonalType } {@link RecordUnclassifiedType } {@link RecordLabType }
	 * {@link RecordMigelType } {@link RecordPhysioType } {@link RecordDrugType }
	 * 
	 * 
	 */
	public List<Object> getRecordTarmedOrRecordCantonalOrRecordUnclassified(){
		if (recordTarmedOrRecordCantonalOrRecordUnclassified == null) {
			recordTarmedOrRecordCantonalOrRecordUnclassified = new ArrayList<Object>();
		}
		return this.recordTarmedOrRecordCantonalOrRecordUnclassified;
	}
	
}
