//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.13 at 12:17:21 PM MEZ 
//

package ch.fd.invoice400.response;

import java.math.BigInteger;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for errorSchemaType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="errorSchemaType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.xmlData.ch/xmlInvoice/XSD>nonEmptyTextType">
 *       &lt;attribute name="err_code" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="err_text" type="{http://www.xmlData.ch/xmlInvoice/XSD}stringType1_350" />
 *       &lt;attribute name="line_number" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *       &lt;attribute name="line_pos" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "errorSchemaType", propOrder = {
	"value"
})
public class ErrorSchemaType {
	
	@XmlValue
	protected String value;
	@XmlAttribute(name = "err_code")
	protected BigInteger errCode;
	@XmlAttribute(name = "err_text")
	protected String errText;
	@XmlAttribute(name = "line_number")
	protected BigInteger lineNumber;
	@XmlAttribute(name = "line_pos")
	protected BigInteger linePos;
	
	/**
	 * Gets the value of the value property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getValue(){
		return value;
	}
	
	/**
	 * Sets the value of the value property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setValue(String value){
		this.value = value;
	}
	
	/**
	 * Gets the value of the errCode property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getErrCode(){
		return errCode;
	}
	
	/**
	 * Sets the value of the errCode property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setErrCode(BigInteger value){
		this.errCode = value;
	}
	
	/**
	 * Gets the value of the errText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getErrText(){
		return errText;
	}
	
	/**
	 * Sets the value of the errText property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setErrText(String value){
		this.errText = value;
	}
	
	/**
	 * Gets the value of the lineNumber property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getLineNumber(){
		return lineNumber;
	}
	
	/**
	 * Sets the value of the lineNumber property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setLineNumber(BigInteger value){
		this.lineNumber = value;
	}
	
	/**
	 * Gets the value of the linePos property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getLinePos(){
		return linePos;
	}
	
	/**
	 * Sets the value of the linePos property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setLinePos(BigInteger value){
		this.linePos = value;
	}
	
}
