//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.13 at 12:17:21 PM MEZ 
//

package ch.fd.invoice400.response;

import java.math.BigInteger;

import javax.xml.datatype.XMLGregorianCalendar;

import org.apache.commons.lang3.StringUtils;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for invoiceType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="invoiceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="biller">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="ean_party" use="required" type="{http://www.xmlData.ch/xmlInvoice/XSD}eanPartyType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="insurance">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="ean_party" use="required" type="{http://www.xmlData.ch/xmlInvoice/XSD}eanPartyType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="reply" type="{http://www.xmlData.ch/xmlInvoice/XSD}replyAddressType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="case_id" type="{http://www.xmlData.ch/xmlInvoice/XSD}stringType1_35" />
 *       &lt;attribute name="invoice_date" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="invoice_id" use="required" type="{http://www.xmlData.ch/xmlInvoice/XSD}stringType1_35" />
 *       &lt;attribute name="invoice_timestamp" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *       &lt;attribute name="response_id" use="required" type="{http://www.xmlData.ch/xmlInvoice/XSD}stringType1_35" />
 *       &lt;attribute name="response_timestamp" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "invoiceType", propOrder = {
	"biller", "insurance", "reply"
})
public class InvoiceType {
	
	@XmlElement(namespace = "http://www.xmlData.ch/xmlInvoice/XSD", required = true)
	protected Biller biller;
	@XmlElement(namespace = "http://www.xmlData.ch/xmlInvoice/XSD", required = true)
	protected Insurance insurance;
	@XmlElement(namespace = "http://www.xmlData.ch/xmlInvoice/XSD", required = true)
	protected ReplyAddressType reply;
	@XmlAttribute(name = "case_id")
	protected String caseId;
	@XmlAttribute(name = "invoice_date", required = true)
	protected XMLGregorianCalendar invoiceDate;
	@XmlAttribute(name = "invoice_id", required = true)
	protected String invoiceId;
	@XmlAttribute(name = "invoice_timestamp", required = true)
	protected BigInteger invoiceTimestamp;
	@XmlAttribute(name = "response_id", required = true)
	protected String responseId;
	@XmlAttribute(name = "response_timestamp", required = true)
	protected BigInteger responseTimestamp;
	
	/**
	 * Gets the value of the biller property.
	 * 
	 * @return possible object is {@link Biller }
	 * 
	 */
	public Biller getBiller(){
		return biller;
	}
	
	/**
	 * Sets the value of the biller property.
	 * 
	 * @param value
	 *            allowed object is {@link Biller }
	 * 
	 */
	public void setBiller(Biller value){
		this.biller = value;
	}
	
	/**
	 * Gets the value of the insurance property.
	 * 
	 * @return possible object is {@link Insurance }
	 * 
	 */
	public Insurance getInsurance(){
		return insurance;
	}
	
	/**
	 * Sets the value of the insurance property.
	 * 
	 * @param value
	 *            allowed object is {@link Insurance }
	 * 
	 */
	public void setInsurance(Insurance value){
		this.insurance = value;
	}
	
	/**
	 * Gets the value of the reply property.
	 * 
	 * @return possible object is {@link ReplyAddressType }
	 * 
	 */
	public ReplyAddressType getReply(){
		return reply;
	}
	
	/**
	 * Sets the value of the reply property.
	 * 
	 * @param value
	 *            allowed object is {@link ReplyAddressType }
	 * 
	 */
	public void setReply(ReplyAddressType value){
		this.reply = value;
	}
	
	/**
	 * Gets the value of the caseId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCaseId(){
		return caseId;
	}
	
	/**
	 * Sets the value of the caseId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCaseId(String value){
		this.caseId = value;
	}
	
	/**
	 * Gets the value of the invoiceDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getInvoiceDate(){
		return invoiceDate;
	}
	
	/**
	 * Sets the value of the invoiceDate property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setInvoiceDate(XMLGregorianCalendar value){
		this.invoiceDate = value;
	}
	
	/**
	 * Gets the value of the invoiceId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getInvoiceId(){
		return invoiceId;
	}
	
	/**
	 * Sets the value of the invoiceId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setInvoiceId(String value){
		this.invoiceId = value;
	}
	
	/**
	 * Gets the value of the invoiceTimestamp property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getInvoiceTimestamp(){
		return invoiceTimestamp;
	}
	
	/**
	 * Sets the value of the invoiceTimestamp property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setInvoiceTimestamp(BigInteger value){
		this.invoiceTimestamp = value;
	}
	
	/**
	 * Gets the value of the responseId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getResponseId(){
		return responseId;
	}
	
	/**
	 * Sets the value of the responseId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setResponseId(String value){
		this.responseId = value;
	}
	
	/**
	 * Gets the value of the responseTimestamp property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getResponseTimestamp(){
		return responseTimestamp;
	}
	
	/**
	 * Sets the value of the responseTimestamp property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setResponseTimestamp(BigInteger value){
		this.responseTimestamp = value;
	}
	
	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;attribute name="ean_party" use="required" type="{http://www.xmlData.ch/xmlInvoice/XSD}eanPartyType" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = StringUtils.EMPTY)
	public static class Biller {
		
		@XmlAttribute(name = "ean_party", required = true)
		protected String eanParty;
		
		/**
		 * Gets the value of the eanParty property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getEanParty(){
			return eanParty;
		}
		
		/**
		 * Sets the value of the eanParty property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setEanParty(String value){
			this.eanParty = value;
		}
		
	}
	
	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;attribute name="ean_party" use="required" type="{http://www.xmlData.ch/xmlInvoice/XSD}eanPartyType" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = StringUtils.EMPTY)
	public static class Insurance {
		
		@XmlAttribute(name = "ean_party", required = true)
		protected String eanParty;
		
		/**
		 * Gets the value of the eanParty property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getEanParty(){
			return eanParty;
		}
		
		/**
		 * Sets the value of the eanParty property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setEanParty(String value){
			this.eanParty = value;
		}
		
	}
	
}
