//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.13 at 12:17:21 PM MEZ 
//

package ch.fd.invoice400.response;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for modifiedErrorType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="modifiedErrorType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.xmlData.ch/xmlInvoice/XSD}errorType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="error_business" type="{http://www.xmlData.ch/xmlInvoice/XSD}errorBusinessType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "modifiedErrorType", propOrder = {
	"errorBusiness"
})
public class ModifiedErrorType extends ErrorType {
	
	@XmlElement(name = "error_business", namespace = "http://www.xmlData.ch/xmlInvoice/XSD")
	protected ErrorBusinessType errorBusiness;
	
	/**
	 * Gets the value of the errorBusiness property.
	 * 
	 * @return possible object is {@link ErrorBusinessType }
	 * 
	 */
	public ErrorBusinessType getErrorBusiness(){
		return errorBusiness;
	}
	
	/**
	 * Sets the value of the errorBusiness property.
	 * 
	 * @param value
	 *            allowed object is {@link ErrorBusinessType }
	 * 
	 */
	public void setErrorBusiness(ErrorBusinessType value){
		this.errorBusiness = value;
	}
	
}
