//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.13 at 12:17:21 PM MEZ 
//

package ch.fd.invoice400.response;

import javax.xml.namespace.QName;

import ch.fd.invoice400.response.InvoiceType.Biller;
import ch.fd.invoice400.response.InvoiceType.Insurance;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the jaxb package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation
 * for XML content. The Java representation of XML content can consist of schema derived interfaces
 * and classes representing the binding of schema type definitions, element declarations and model
 * groups. Factory methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {
	
	private final static QName _Response_QNAME = new QName("http://www.xmlData.ch/xmlInvoice/XSD",
		"response");
	
	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema derived classes
	 * for package: jaxb
	 * 
	 */
	public ObjectFactory(){}
	
	/**
	 * Create an instance of {@link RecordMigelType }
	 * 
	 */
	public RecordMigelType createRecordMigelType(){
		return new RecordMigelType();
	}
	
	/**
	 * Create an instance of {@link HeaderType }
	 * 
	 */
	public HeaderType createHeaderType(){
		return new HeaderType();
	}
	
	/**
	 * Create an instance of {@link RecordLabType }
	 * 
	 */
	public RecordLabType createRecordLabType(){
		return new RecordLabType();
	}
	
	/**
	 * Create an instance of {@link Esr9Type }
	 * 
	 */
	public Esr9Type createEsr9Type(){
		return new Esr9Type();
	}
	
	/**
	 * Create an instance of {@link CalledInType }
	 * 
	 */
	public CalledInType createCalledInType(){
		return new CalledInType();
	}
	
	/**
	 * Create an instance of {@link InvoicePaidType }
	 * 
	 */
	public InvoicePaidType createInvoicePaidType(){
		return new InvoicePaidType();
	}
	
	/**
	 * Create an instance of {@link GeneratorType }
	 * 
	 */
	public GeneratorType createGeneratorType(){
		return new GeneratorType();
	}
	
	/**
	 * Create an instance of {@link ReplyContactType }
	 * 
	 */
	public ReplyContactType createReplyContactType(){
		return new ReplyContactType();
	}
	
	/**
	 * Create an instance of {@link PrologType }
	 * 
	 */
	public PrologType createPrologType(){
		return new PrologType();
	}
	
	/**
	 * Create an instance of {@link ServicesType }
	 * 
	 */
	public ServicesType createServicesType(){
		return new ServicesType();
	}
	
	/**
	 * Create an instance of {@link RecordTarmedType }
	 * 
	 */
	public RecordTarmedType createRecordTarmedType(){
		return new RecordTarmedType();
	}
	
	/**
	 * Create an instance of {@link RecordPhysioType }
	 * 
	 */
	public RecordPhysioType createRecordPhysioType(){
		return new RecordPhysioType();
	}
	
	/**
	 * Create an instance of {@link RejectedErrorType }
	 * 
	 */
	public RejectedErrorType createRejectedErrorType(){
		return new RejectedErrorType();
	}
	
	/**
	 * Create an instance of {@link HeaderPartyType }
	 * 
	 */
	public HeaderPartyType createHeaderPartyType(){
		return new HeaderPartyType();
	}
	
	/**
	 * Create an instance of {@link OnlineAddressType }
	 * 
	 */
	public OnlineAddressType createOnlineAddressType(){
		return new OnlineAddressType();
	}
	
	/**
	 * Create an instance of {@link ErrorBusinessType }
	 * 
	 */
	public ErrorBusinessType createErrorBusinessType(){
		return new ErrorBusinessType();
	}
	
	/**
	 * Create an instance of {@link EsrRedType }
	 * 
	 */
	public EsrRedType createEsrRedType(){
		return new EsrRedType();
	}
	
	/**
	 * Create an instance of {@link Esr5Type }
	 * 
	 */
	public Esr5Type createEsr5Type(){
		return new Esr5Type();
	}
	
	/**
	 * Create an instance of {@link AnnulmentType }
	 * 
	 */
	public AnnulmentType createAnnulmentType(){
		return new AnnulmentType();
	}
	
	/**
	 * Create an instance of {@link SoftwareType }
	 * 
	 */
	public SoftwareType createSoftwareType(){
		return new SoftwareType();
	}
	
	/**
	 * Create an instance of {@link DataValidatorType }
	 * 
	 */
	public DataValidatorType createDataValidatorType(){
		return new DataValidatorType();
	}
	
	/**
	 * Create an instance of {@link RecordDrugType }
	 * 
	 */
	public RecordDrugType createRecordDrugType(){
		return new RecordDrugType();
	}
	
	/**
	 * Create an instance of {@link InvoiceType }
	 * 
	 */
	public InvoiceType createInvoiceType(){
		return new InvoiceType();
	}
	
	/**
	 * Create an instance of {@link ErrorSchemaType }
	 * 
	 */
	public ErrorSchemaType createErrorSchemaType(){
		return new ErrorSchemaType();
	}
	
	/**
	 * Create an instance of {@link ModifiedErrorType }
	 * 
	 */
	public ModifiedErrorType createModifiedErrorType(){
		return new ModifiedErrorType();
	}
	
	/**
	 * Create an instance of {@link ZipType }
	 * 
	 */
	public ZipType createZipType(){
		return new ZipType();
	}
	
	/**
	 * Create an instance of {@link CalledInErrorType }
	 * 
	 */
	public CalledInErrorType createCalledInErrorType(){
		return new CalledInErrorType();
	}
	
	/**
	 * Create an instance of {@link NotificationType }
	 * 
	 */
	public NotificationType createNotificationType(){
		return new NotificationType();
	}
	
	/**
	 * Create an instance of {@link Insurance }
	 * 
	 */
	public Insurance createInvoiceTypeInsurance(){
		return new Insurance();
	}
	
	/**
	 * Create an instance of {@link PostalAddressType }
	 * 
	 */
	public PostalAddressType createPostalAddressType(){
		return new PostalAddressType();
	}
	
	/**
	 * Create an instance of {@link ReplyCompanyType }
	 * 
	 */
	public ReplyCompanyType createReplyCompanyType(){
		return new ReplyCompanyType();
	}
	
	/**
	 * Create an instance of {@link TelecomAddressType }
	 * 
	 */
	public TelecomAddressType createTelecomAddressType(){
		return new TelecomAddressType();
	}
	
	/**
	 * Create an instance of {@link ErrorType }
	 * 
	 */
	public ErrorType createErrorType(){
		return new ErrorType();
	}
	
	/**
	 * Create an instance of {@link ResponseType }
	 * 
	 */
	public ResponseType createResponseType(){
		return new ResponseType();
	}
	
	/**
	 * Create an instance of {@link Biller }
	 * 
	 */
	public Biller createInvoiceTypeBiller(){
		return new Biller();
	}
	
	/**
	 * Create an instance of {@link BankAddressType }
	 * 
	 */
	public BankAddressType createBankAddressType(){
		return new BankAddressType();
	}
	
	/**
	 * Create an instance of {@link RecordCantonalType }
	 * 
	 */
	public RecordCantonalType createRecordCantonalType(){
		return new RecordCantonalType();
	}
	
	/**
	 * Create an instance of {@link RejectedType }
	 * 
	 */
	public RejectedType createRejectedType(){
		return new RejectedType();
	}
	
	/**
	 * Create an instance of {@link BalanceType }
	 * 
	 */
	public BalanceType createBalanceType(){
		return new BalanceType();
	}
	
	/**
	 * Create an instance of {@link ModifiedType }
	 * 
	 */
	public ModifiedType createModifiedType(){
		return new ModifiedType();
	}
	
	/**
	 * Create an instance of {@link XtraElementType }
	 * 
	 */
	public XtraElementType createXtraElementType(){
		return new XtraElementType();
	}
	
	/**
	 * Create an instance of {@link StatusType }
	 * 
	 */
	public StatusType createStatusType(){
		return new StatusType();
	}
	
	/**
	 * Create an instance of {@link BankCompanyType }
	 * 
	 */
	public BankCompanyType createBankCompanyType(){
		return new BankCompanyType();
	}
	
	/**
	 * Create an instance of {@link CreditAdviceType }
	 * 
	 */
	public CreditAdviceType createCreditAdviceType(){
		return new CreditAdviceType();
	}
	
	/**
	 * Create an instance of {@link RecordUnclassifiedType }
	 * 
	 */
	public RecordUnclassifiedType createRecordUnclassifiedType(){
		return new RecordUnclassifiedType();
	}
	
	/**
	 * Create an instance of {@link ReplyAddressType }
	 * 
	 */
	public ReplyAddressType createReplyAddressType(){
		return new ReplyAddressType();
	}
	
	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link ResponseType }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "http://www.xmlData.ch/xmlInvoice/XSD", name = "response")
	public JAXBElement<ResponseType> createResponse(ResponseType value){
		return new JAXBElement<ResponseType>(_Response_QNAME, ResponseType.class, null, value);
	}
	
}
