//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.13 at 12:17:21 PM MEZ 
//

package ch.fd.invoice400.response;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for statusType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="statusType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="rejected" type="{http://www.xmlData.ch/xmlInvoice/XSD}rejectedType"/>
 *         &lt;element name="calledIn" type="{http://www.xmlData.ch/xmlInvoice/XSD}calledInType"/>
 *         &lt;element name="pending" type="{http://www.xmlData.ch/xmlInvoice/XSD}notificationType"/>
 *         &lt;element name="resend" type="{http://www.xmlData.ch/xmlInvoice/XSD}notificationType"/>
 *         &lt;element name="modified" type="{http://www.xmlData.ch/xmlInvoice/XSD}modifiedType"/>
 *         &lt;element name="annulment" type="{http://www.xmlData.ch/xmlInvoice/XSD}annulmentType"/>
 *         &lt;element name="creditAdvice" type="{http://www.xmlData.ch/xmlInvoice/XSD}creditAdviceType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "statusType", propOrder = {
	"rejected", "calledIn", "pending", "resend", "modified", "annulment", "creditAdvice"
})
public class StatusType {
	
	@XmlElement(namespace = "http://www.xmlData.ch/xmlInvoice/XSD")
	protected RejectedType rejected;
	@XmlElement(namespace = "http://www.xmlData.ch/xmlInvoice/XSD")
	protected CalledInType calledIn;
	@XmlElement(namespace = "http://www.xmlData.ch/xmlInvoice/XSD")
	protected NotificationType pending;
	@XmlElement(namespace = "http://www.xmlData.ch/xmlInvoice/XSD")
	protected NotificationType resend;
	@XmlElement(namespace = "http://www.xmlData.ch/xmlInvoice/XSD")
	protected ModifiedType modified;
	@XmlElement(namespace = "http://www.xmlData.ch/xmlInvoice/XSD")
	protected AnnulmentType annulment;
	@XmlElement(namespace = "http://www.xmlData.ch/xmlInvoice/XSD")
	protected CreditAdviceType creditAdvice;
	
	/**
	 * Gets the value of the rejected property.
	 * 
	 * @return possible object is {@link RejectedType }
	 * 
	 */
	public RejectedType getRejected(){
		return rejected;
	}
	
	/**
	 * Sets the value of the rejected property.
	 * 
	 * @param value
	 *            allowed object is {@link RejectedType }
	 * 
	 */
	public void setRejected(RejectedType value){
		this.rejected = value;
	}
	
	/**
	 * Gets the value of the calledIn property.
	 * 
	 * @return possible object is {@link CalledInType }
	 * 
	 */
	public CalledInType getCalledIn(){
		return calledIn;
	}
	
	/**
	 * Sets the value of the calledIn property.
	 * 
	 * @param value
	 *            allowed object is {@link CalledInType }
	 * 
	 */
	public void setCalledIn(CalledInType value){
		this.calledIn = value;
	}
	
	/**
	 * Gets the value of the pending property.
	 * 
	 * @return possible object is {@link NotificationType }
	 * 
	 */
	public NotificationType getPending(){
		return pending;
	}
	
	/**
	 * Sets the value of the pending property.
	 * 
	 * @param value
	 *            allowed object is {@link NotificationType }
	 * 
	 */
	public void setPending(NotificationType value){
		this.pending = value;
	}
	
	/**
	 * Gets the value of the resend property.
	 * 
	 * @return possible object is {@link NotificationType }
	 * 
	 */
	public NotificationType getResend(){
		return resend;
	}
	
	/**
	 * Sets the value of the resend property.
	 * 
	 * @param value
	 *            allowed object is {@link NotificationType }
	 * 
	 */
	public void setResend(NotificationType value){
		this.resend = value;
	}
	
	/**
	 * Gets the value of the modified property.
	 * 
	 * @return possible object is {@link ModifiedType }
	 * 
	 */
	public ModifiedType getModified(){
		return modified;
	}
	
	/**
	 * Sets the value of the modified property.
	 * 
	 * @param value
	 *            allowed object is {@link ModifiedType }
	 * 
	 */
	public void setModified(ModifiedType value){
		this.modified = value;
	}
	
	/**
	 * Gets the value of the annulment property.
	 * 
	 * @return possible object is {@link AnnulmentType }
	 * 
	 */
	public AnnulmentType getAnnulment(){
		return annulment;
	}
	
	/**
	 * Sets the value of the annulment property.
	 * 
	 * @param value
	 *            allowed object is {@link AnnulmentType }
	 * 
	 */
	public void setAnnulment(AnnulmentType value){
		this.annulment = value;
	}
	
	/**
	 * Gets the value of the creditAdvice property.
	 * 
	 * @return possible object is {@link CreditAdviceType }
	 * 
	 */
	public CreditAdviceType getCreditAdvice(){
		return creditAdvice;
	}
	
	/**
	 * Sets the value of the creditAdvice property.
	 * 
	 * @param value
	 *            allowed object is {@link CreditAdviceType }
	 * 
	 */
	public void setCreditAdvice(CreditAdviceType value){
		this.creditAdvice = value;
	}
	
}
