//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.13 at 12:17:21 PM MEZ 
//

package ch.fd.invoice400.response;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for zipType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="zipType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.xmlData.ch/xmlInvoice/XSD>stringType1_9">
 *       &lt;attribute name="countrycode" type="{http://www.xmlData.ch/xmlInvoice/XSD}stringType1_3" default="CH" />
 *       &lt;attribute name="statecode" type="{http://www.xmlData.ch/xmlInvoice/XSD}stringType1_9" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "zipType", propOrder = {
	"value"
})
public class ZipType {
	
	@XmlValue
	protected String value;
	@XmlAttribute
	protected String countrycode;
	@XmlAttribute
	protected String statecode;
	
	/**
	 * Gets the value of the value property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getValue(){
		return value;
	}
	
	/**
	 * Sets the value of the value property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setValue(String value){
		this.value = value;
	}
	
	/**
	 * Gets the value of the countrycode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCountrycode(){
		if (countrycode == null) {
			return "CH";
		} else {
			return countrycode;
		}
	}
	
	/**
	 * Sets the value of the countrycode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCountrycode(String value){
		this.countrycode = value;
	}
	
	/**
	 * Gets the value of the statecode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStatecode(){
		return statecode;
	}
	
	/**
	 * Sets the value of the statecode property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setStatecode(String value){
		this.statecode = value;
	}
	
}
