//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.18 at 03:48:09 PM CET 
//


package ch.fd.invoice440.request;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for bodyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bodyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="prolog" type="{http://www.forum-datenaustausch.ch/invoice}prologType"/>
 *         &lt;element name="remark" type="{http://www.forum-datenaustausch.ch/invoice}stringType1_350" minOccurs="0"/>
 *         &lt;element name="balance" type="{http://www.forum-datenaustausch.ch/invoice}balanceType"/>
 *         &lt;choice>
 *           &lt;element name="esr5" type="{http://www.forum-datenaustausch.ch/invoice}esr5Type"/>
 *           &lt;element name="esr9" type="{http://www.forum-datenaustausch.ch/invoice}esr9Type"/>
 *           &lt;element name="esrRed" type="{http://www.forum-datenaustausch.ch/invoice}esrRedType"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element name="tiers_garant" type="{http://www.forum-datenaustausch.ch/invoice}garantType"/>
 *           &lt;element name="tiers_payant" type="{http://www.forum-datenaustausch.ch/invoice}payantType"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element name="kvg" type="{http://www.forum-datenaustausch.ch/invoice}kvgLawType"/>
 *           &lt;element name="vvg" type="{http://www.forum-datenaustausch.ch/invoice}vvgLawType"/>
 *           &lt;element name="uvg" type="{http://www.forum-datenaustausch.ch/invoice}uvgLawType"/>
 *           &lt;element name="ivg" type="{http://www.forum-datenaustausch.ch/invoice}ivgLawType"/>
 *           &lt;element name="mvg" type="{http://www.forum-datenaustausch.ch/invoice}mvgLawType"/>
 *           &lt;element name="org" type="{http://www.forum-datenaustausch.ch/invoice}orgLawType"/>
 *         &lt;/choice>
 *         &lt;element name="treatment" type="{http://www.forum-datenaustausch.ch/invoice}treatmentType"/>
 *         &lt;element name="services" type="{http://www.forum-datenaustausch.ch/invoice}servicesType"/>
 *         &lt;element name="documents" type="{http://www.forum-datenaustausch.ch/invoice}documentsType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="role_title" type="{http://www.forum-datenaustausch.ch/invoice}stringType1_35" />
 *       &lt;attribute name="role" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="physician"/>
 *             &lt;enumeration value="physiotherapist"/>
 *             &lt;enumeration value="chiropractor"/>
 *             &lt;enumeration value="ergotherapist"/>
 *             &lt;enumeration value="nutritionist"/>
 *             &lt;enumeration value="midwife"/>
 *             &lt;enumeration value="logotherapist"/>
 *             &lt;enumeration value="hospital"/>
 *             &lt;enumeration value="pharmacist"/>
 *             &lt;enumeration value="dentist"/>
 *             &lt;enumeration value="labtechnician"/>
 *             &lt;enumeration value="dentaltechnician"/>
 *             &lt;enumeration value="othertechnician"/>
 *             &lt;enumeration value="psychologist"/>
 *             &lt;enumeration value="wholesaler"/>
 *             &lt;enumeration value="nursingstaff"/>
 *             &lt;enumeration value="transport"/>
 *             &lt;enumeration value="druggist"/>
 *             &lt;enumeration value="naturopathicdoctor"/>
 *             &lt;enumeration value="naturopathictherapist"/>
 *             &lt;enumeration value="other"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="place" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="practice"/>
 *             &lt;enumeration value="hospital"/>
 *             &lt;enumeration value="lab"/>
 *             &lt;enumeration value="association"/>
 *             &lt;enumeration value="company"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bodyType", propOrder = {
    "prolog",
    "remark",
    "balance",
    "esr5",
    "esr9",
    "esrRed",
    "tiersGarant",
    "tiersPayant",
    "kvg",
    "vvg",
    "uvg",
    "ivg",
    "mvg",
    "org",
    "treatment",
    "services",
    "documents"
})
public class BodyType {

    @XmlElement(required = true)
    protected PrologType prolog;
    protected String remark;
    @XmlElement(required = true)
    protected BalanceType balance;
    protected Esr5Type esr5;
    protected Esr9Type esr9;
    protected EsrRedType esrRed;
    @XmlElement(name = "tiers_garant")
    protected GarantType tiersGarant;
    @XmlElement(name = "tiers_payant")
    protected PayantType tiersPayant;
    protected KvgLawType kvg;
    protected VvgLawType vvg;
    protected UvgLawType uvg;
    protected IvgLawType ivg;
    protected MvgLawType mvg;
    protected OrgLawType org;
    @XmlElement(required = true)
    protected TreatmentType treatment;
    @XmlElement(required = true)
    protected ServicesType services;
    protected DocumentsType documents;
    @XmlAttribute(name = "role_title")
    protected String roleTitle;
    @XmlAttribute(name = "role", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String role;
    @XmlAttribute(name = "place", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String place;

    /**
     * Gets the value of the prolog property.
     * 
     * @return
     *     possible object is
     *     {@link PrologType }
     *     
     */
    public PrologType getProlog() {
        return prolog;
    }

    /**
     * Sets the value of the prolog property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrologType }
     *     
     */
    public void setProlog(PrologType value) {
        this.prolog = value;
    }

    /**
     * Gets the value of the remark property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemark() {
        return remark;
    }

    /**
     * Sets the value of the remark property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemark(String value) {
        this.remark = value;
    }

    /**
     * Gets the value of the balance property.
     * 
     * @return
     *     possible object is
     *     {@link BalanceType }
     *     
     */
    public BalanceType getBalance() {
        return balance;
    }

    /**
     * Sets the value of the balance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BalanceType }
     *     
     */
    public void setBalance(BalanceType value) {
        this.balance = value;
    }

    /**
     * Gets the value of the esr5 property.
     * 
     * @return
     *     possible object is
     *     {@link Esr5Type }
     *     
     */
    public Esr5Type getEsr5() {
        return esr5;
    }

    /**
     * Sets the value of the esr5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Esr5Type }
     *     
     */
    public void setEsr5(Esr5Type value) {
        this.esr5 = value;
    }

    /**
     * Gets the value of the esr9 property.
     * 
     * @return
     *     possible object is
     *     {@link Esr9Type }
     *     
     */
    public Esr9Type getEsr9() {
        return esr9;
    }

    /**
     * Sets the value of the esr9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Esr9Type }
     *     
     */
    public void setEsr9(Esr9Type value) {
        this.esr9 = value;
    }

    /**
     * Gets the value of the esrRed property.
     * 
     * @return
     *     possible object is
     *     {@link EsrRedType }
     *     
     */
    public EsrRedType getEsrRed() {
        return esrRed;
    }

    /**
     * Sets the value of the esrRed property.
     * 
     * @param value
     *     allowed object is
     *     {@link EsrRedType }
     *     
     */
    public void setEsrRed(EsrRedType value) {
        this.esrRed = value;
    }

    /**
     * Gets the value of the tiersGarant property.
     * 
     * @return
     *     possible object is
     *     {@link GarantType }
     *     
     */
    public GarantType getTiersGarant() {
        return tiersGarant;
    }

    /**
     * Sets the value of the tiersGarant property.
     * 
     * @param value
     *     allowed object is
     *     {@link GarantType }
     *     
     */
    public void setTiersGarant(GarantType value) {
        this.tiersGarant = value;
    }

    /**
     * Gets the value of the tiersPayant property.
     * 
     * @return
     *     possible object is
     *     {@link PayantType }
     *     
     */
    public PayantType getTiersPayant() {
        return tiersPayant;
    }

    /**
     * Sets the value of the tiersPayant property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayantType }
     *     
     */
    public void setTiersPayant(PayantType value) {
        this.tiersPayant = value;
    }

    /**
     * Gets the value of the kvg property.
     * 
     * @return
     *     possible object is
     *     {@link KvgLawType }
     *     
     */
    public KvgLawType getKvg() {
        return kvg;
    }

    /**
     * Sets the value of the kvg property.
     * 
     * @param value
     *     allowed object is
     *     {@link KvgLawType }
     *     
     */
    public void setKvg(KvgLawType value) {
        this.kvg = value;
    }

    /**
     * Gets the value of the vvg property.
     * 
     * @return
     *     possible object is
     *     {@link VvgLawType }
     *     
     */
    public VvgLawType getVvg() {
        return vvg;
    }

    /**
     * Sets the value of the vvg property.
     * 
     * @param value
     *     allowed object is
     *     {@link VvgLawType }
     *     
     */
    public void setVvg(VvgLawType value) {
        this.vvg = value;
    }

    /**
     * Gets the value of the uvg property.
     * 
     * @return
     *     possible object is
     *     {@link UvgLawType }
     *     
     */
    public UvgLawType getUvg() {
        return uvg;
    }

    /**
     * Sets the value of the uvg property.
     * 
     * @param value
     *     allowed object is
     *     {@link UvgLawType }
     *     
     */
    public void setUvg(UvgLawType value) {
        this.uvg = value;
    }

    /**
     * Gets the value of the ivg property.
     * 
     * @return
     *     possible object is
     *     {@link IvgLawType }
     *     
     */
    public IvgLawType getIvg() {
        return ivg;
    }

    /**
     * Sets the value of the ivg property.
     * 
     * @param value
     *     allowed object is
     *     {@link IvgLawType }
     *     
     */
    public void setIvg(IvgLawType value) {
        this.ivg = value;
    }

    /**
     * Gets the value of the mvg property.
     * 
     * @return
     *     possible object is
     *     {@link MvgLawType }
     *     
     */
    public MvgLawType getMvg() {
        return mvg;
    }

    /**
     * Sets the value of the mvg property.
     * 
     * @param value
     *     allowed object is
     *     {@link MvgLawType }
     *     
     */
    public void setMvg(MvgLawType value) {
        this.mvg = value;
    }

    /**
     * Gets the value of the org property.
     * 
     * @return
     *     possible object is
     *     {@link OrgLawType }
     *     
     */
    public OrgLawType getOrg() {
        return org;
    }

    /**
     * Sets the value of the org property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrgLawType }
     *     
     */
    public void setOrg(OrgLawType value) {
        this.org = value;
    }

    /**
     * Gets the value of the treatment property.
     * 
     * @return
     *     possible object is
     *     {@link TreatmentType }
     *     
     */
    public TreatmentType getTreatment() {
        return treatment;
    }

    /**
     * Sets the value of the treatment property.
     * 
     * @param value
     *     allowed object is
     *     {@link TreatmentType }
     *     
     */
    public void setTreatment(TreatmentType value) {
        this.treatment = value;
    }

    /**
     * Gets the value of the services property.
     * 
     * @return
     *     possible object is
     *     {@link ServicesType }
     *     
     */
    public ServicesType getServices() {
        return services;
    }

    /**
     * Sets the value of the services property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServicesType }
     *     
     */
    public void setServices(ServicesType value) {
        this.services = value;
    }

    /**
     * Gets the value of the documents property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentsType }
     *     
     */
    public DocumentsType getDocuments() {
        return documents;
    }

    /**
     * Sets the value of the documents property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentsType }
     *     
     */
    public void setDocuments(DocumentsType value) {
        this.documents = value;
    }

    /**
     * Gets the value of the roleTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoleTitle() {
        return roleTitle;
    }

    /**
     * Sets the value of the roleTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoleTitle(String value) {
        this.roleTitle = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRole(String value) {
        this.role = value;
    }

    /**
     * Gets the value of the place property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlace() {
        return place;
    }

    /**
     * Sets the value of the place property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlace(String value) {
        this.place = value;
    }

}
