//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.18 at 03:48:09 PM CET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.forum-datenaustausch.ch/invoice", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED, xmlns = {
		@jakarta.xml.bind.annotation.XmlNs(prefix = "invoice", namespaceURI = "http://www.forum-datenaustausch.ch/invoice"),
		@jakarta.xml.bind.annotation.XmlNs(prefix = "ds", namespaceURI = "http://www.w3.org/2000/09/xmldsig#"),
		@jakarta.xml.bind.annotation.XmlNs(prefix = "xenc", namespaceURI = "http://www.w3.org/2001/04/xmlenc#")
})
package ch.fd.invoice440.request;

