//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.18 at 03:48:09 PM CET 
//


package ch.fd.invoice440.request;

import javax.xml.datatype.XMLGregorianCalendar;

import org.apache.commons.lang3.StringUtils;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for processingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="processingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="transport" type="{http://www.forum-datenaustausch.ch/invoice}transportType"/>
 *         &lt;element name="validations" type="{http://www.forum-datenaustausch.ch/invoice}validationsType" minOccurs="0"/>
 *         &lt;element name="demand" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="tc_demand_id" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *                 &lt;attribute name="tc_token" use="required" type="{http://www.forum-datenaustausch.ch/invoice}stringType1_100" />
 *                 &lt;attribute name="insurance_demand_date" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                 &lt;attribute name="insurance_demand_id" type="{http://www.forum-datenaustausch.ch/invoice}stringType1_35" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="print_at_intermediate" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="print_patient_copy" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "processingType", propOrder = {
    "transport",
    "validations",
    "demand"
})
public class ProcessingType {

    @XmlElement(required = true)
    protected TransportType transport;
    protected ValidationsType validations;
    protected ProcessingType.Demand demand;
    @XmlAttribute(name = "print_at_intermediate")
    protected Boolean printAtIntermediate;
    @XmlAttribute(name = "print_patient_copy")
    protected Boolean printPatientCopy;

    /**
     * Gets the value of the transport property.
     * 
     * @return
     *     possible object is
     *     {@link TransportType }
     *     
     */
    public TransportType getTransport() {
        return transport;
    }

    /**
     * Sets the value of the transport property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransportType }
     *     
     */
    public void setTransport(TransportType value) {
        this.transport = value;
    }

    /**
     * Gets the value of the validations property.
     * 
     * @return
     *     possible object is
     *     {@link ValidationsType }
     *     
     */
    public ValidationsType getValidations() {
        return validations;
    }

    /**
     * Sets the value of the validations property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidationsType }
     *     
     */
    public void setValidations(ValidationsType value) {
        this.validations = value;
    }

    /**
     * Gets the value of the demand property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessingType.Demand }
     *     
     */
    public ProcessingType.Demand getDemand() {
        return demand;
    }

    /**
     * Sets the value of the demand property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessingType.Demand }
     *     
     */
    public void setDemand(ProcessingType.Demand value) {
        this.demand = value;
    }

    /**
     * Gets the value of the printAtIntermediate property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isPrintAtIntermediate() {
        if (printAtIntermediate == null) {
            return false;
        } else {
            return printAtIntermediate;
        }
    }

    /**
     * Sets the value of the printAtIntermediate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPrintAtIntermediate(Boolean value) {
        this.printAtIntermediate = value;
    }

    /**
     * Gets the value of the printPatientCopy property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isPrintPatientCopy() {
        if (printPatientCopy == null) {
            return false;
        } else {
            return printPatientCopy;
        }
    }

    /**
     * Sets the value of the printPatientCopy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPrintPatientCopy(Boolean value) {
        this.printPatientCopy = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="tc_demand_id" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
     *       &lt;attribute name="tc_token" use="required" type="{http://www.forum-datenaustausch.ch/invoice}stringType1_100" />
     *       &lt;attribute name="insurance_demand_date" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *       &lt;attribute name="insurance_demand_id" type="{http://www.forum-datenaustausch.ch/invoice}stringType1_35" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = StringUtils.EMPTY)
    public static class Demand {

        @XmlAttribute(name = "tc_demand_id", required = true)
        protected long tcDemandId;
        @XmlAttribute(name = "tc_token", required = true)
        protected String tcToken;
        @XmlAttribute(name = "insurance_demand_date", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar insuranceDemandDate;
        @XmlAttribute(name = "insurance_demand_id")
        protected String insuranceDemandId;

        /**
         * Gets the value of the tcDemandId property.
         * 
         */
        public long getTcDemandId() {
            return tcDemandId;
        }

        /**
         * Sets the value of the tcDemandId property.
         * 
         */
        public void setTcDemandId(long value) {
            this.tcDemandId = value;
        }

        /**
         * Gets the value of the tcToken property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTcToken() {
            return tcToken;
        }

        /**
         * Sets the value of the tcToken property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTcToken(String value) {
            this.tcToken = value;
        }

        /**
         * Gets the value of the insuranceDemandDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getInsuranceDemandDate() {
            return insuranceDemandDate;
        }

        /**
         * Sets the value of the insuranceDemandDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setInsuranceDemandDate(XMLGregorianCalendar value) {
            this.insuranceDemandDate = value;
        }

        /**
         * Gets the value of the insuranceDemandId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInsuranceDemandId() {
            return insuranceDemandId;
        }

        /**
         * Sets the value of the insuranceDemandId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInsuranceDemandId(String value) {
            this.insuranceDemandId = value;
        }

    }

}
