//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.18 at 03:48:09 PM CET 
//


package ch.fd.invoice440.request;

import org.apache.commons.lang3.StringUtils;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for recordDrugType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="recordDrugType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.forum-datenaustausch.ch/invoice}recordServiceType">
 *       &lt;sequence>
 *         &lt;element name="xtra_drug" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="indicated" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="iocm_category">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *                       &lt;enumeration value="A"/>
 *                       &lt;enumeration value="B"/>
 *                       &lt;enumeration value="C"/>
 *                       &lt;enumeration value="D"/>
 *                       &lt;enumeration value="E"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="delivery" default="first">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *                       &lt;enumeration value="first"/>
 *                       &lt;enumeration value="repeated"/>
 *                       &lt;enumeration value="permanent"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="regulation_attributes" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" default="0" />
 *                 &lt;attribute name="limitation" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="tariff_type" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[0-9A-Z]{3}"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "recordDrugType", propOrder = {
    "xtraDrug"
})
public class RecordDrugType
    extends RecordServiceType
{

    @XmlElement(name = "xtra_drug")
    protected RecordDrugType.XtraDrug xtraDrug;
    @XmlAttribute(name = "tariff_type", required = true)
    protected String tariffType;

    /**
     * Gets the value of the xtraDrug property.
     * 
     * @return
     *     possible object is
     *     {@link RecordDrugType.XtraDrug }
     *     
     */
    public RecordDrugType.XtraDrug getXtraDrug() {
        return xtraDrug;
    }

    /**
     * Sets the value of the xtraDrug property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecordDrugType.XtraDrug }
     *     
     */
    public void setXtraDrug(RecordDrugType.XtraDrug value) {
        this.xtraDrug = value;
    }

    /**
     * Gets the value of the tariffType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTariffType() {
        return tariffType;
    }

    /**
     * Sets the value of the tariffType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTariffType(String value) {
        this.tariffType = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="indicated" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="iocm_category">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
     *             &lt;enumeration value="A"/>
     *             &lt;enumeration value="B"/>
     *             &lt;enumeration value="C"/>
     *             &lt;enumeration value="D"/>
     *             &lt;enumeration value="E"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="delivery" default="first">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
     *             &lt;enumeration value="first"/>
     *             &lt;enumeration value="repeated"/>
     *             &lt;enumeration value="permanent"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="regulation_attributes" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" default="0" />
     *       &lt;attribute name="limitation" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = StringUtils.EMPTY)
    public static class XtraDrug {

        @XmlAttribute(name = "indicated")
        protected Boolean indicated;
        @XmlAttribute(name = "iocm_category")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String iocmCategory;
        @XmlAttribute(name = "delivery")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String delivery;
        @XmlAttribute(name = "regulation_attributes")
        @XmlSchemaType(name = "unsignedInt")
        protected Long regulationAttributes;
        @XmlAttribute(name = "limitation")
        protected Boolean limitation;

        /**
         * Gets the value of the indicated property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isIndicated() {
            return indicated;
        }

        /**
         * Sets the value of the indicated property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setIndicated(Boolean value) {
            this.indicated = value;
        }

        /**
         * Gets the value of the iocmCategory property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIocmCategory() {
            return iocmCategory;
        }

        /**
         * Sets the value of the iocmCategory property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIocmCategory(String value) {
            this.iocmCategory = value;
        }

        /**
         * Gets the value of the delivery property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDelivery() {
            if (delivery == null) {
                return "first";
            } else {
                return delivery;
            }
        }

        /**
         * Sets the value of the delivery property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDelivery(String value) {
            this.delivery = value;
        }

        /**
         * Gets the value of the regulationAttributes property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public long getRegulationAttributes() {
            if (regulationAttributes == null) {
                return  0L;
            } else {
                return regulationAttributes;
            }
        }

        /**
         * Sets the value of the regulationAttributes property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setRegulationAttributes(Long value) {
            this.regulationAttributes = value;
        }

        /**
         * Gets the value of the limitation property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isLimitation() {
            return limitation;
        }

        /**
         * Sets the value of the limitation property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setLimitation(Boolean value) {
            this.limitation = value;
        }

    }

}
