<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="arzttarife" nsURI="http://ch.elexis.base/model/arzttarife" nsPrefix="ch.elexis.arzttarife.ch.model">
  <eSubpackages name="tarmed" nsURI="http://ch.elexis.base/model/arzttarife/tarmed"
      nsPrefix="ch.elexis.arzttarife.ch.tarmed.model">
    <eClassifiers xsi:type="ecore:EClass" name="ITarmedLeistung" abstract="true" interface="true"
        eSuperTypes="../ch.elexis.core/model/model.ecore#//IService">
      <eOperations name="getServiceGroups" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eParameters name="date" eType="ecore:EDataType ../ch.elexis.core/model/types.ecore#//LocalDate"/>
      </eOperations>
      <eOperations name="getServiceBlocks" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eParameters name="date" eType="ecore:EDataType ../ch.elexis.core/model/types.ecore#//LocalDate"/>
      </eOperations>
      <eOperations name="requiresSide" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="getAL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eParameters name="mandator" eType="ecore:EClass ../ch.elexis.core/model/model.ecore#//IMandator"/>
      </eOperations>
      <eOperations name="getKumulations">
        <eGenericType eClassifier="ecore:EClass ../ch.elexis.core/model/types.ecore#//List">
          <eTypeArguments eClassifier="#//tarmed/ITarmedKumulation"/>
        </eGenericType>
        <eParameters name="type" eType="#//tarmed/TarmedKumulationArt"/>
      </eOperations>
      <eOperations name="getHierarchy">
        <eGenericType eClassifier="ecore:EClass ../ch.elexis.core/model/types.ecore#//List">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eGenericType>
        <eParameters name="date" eType="ecore:EDataType ../ch.elexis.core/model/types.ecore#//LocalDate"/>
      </eOperations>
      <eOperations name="isZuschlagsleistung" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="AL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="TL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="digniQuali" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="digniQuanti" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="exclusion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="extension" eType="#//tarmed/ITarmedExtension"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//tarmed/ITarmedLeistung"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validFrom" eType="ecore:EDataType ../ch.elexis.core/model/types.ecore#//LocalDate"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validTo" eType="ecore:EDataType ../ch.elexis.core/model/types.ecore#//LocalDate"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceTyp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="law" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sparte" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="chapter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nickname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ITarmedExtension" abstract="true"
        interface="true" eSuperTypes="../ch.elexis.core/model/model.ecore#//Identifiable ../ch.elexis.core/model/model.ecore#//Deleteable ../ch.elexis.core/model/model.ecore#//WithExtInfo">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="limits" changeable="false"
          transient="true">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eGenericType>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="medInterpretation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="techInterpretation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ITarmedGroup" abstract="true" interface="true"
        eSuperTypes="../ch.elexis.core/model/model.ecore#//Deleteable ../ch.elexis.core/model/model.ecore#//Identifiable">
      <eOperations name="validAt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="reference" eType="ecore:EDataType ../ch.elexis.core/model/types.ecore#//LocalDate"/>
      </eOperations>
      <eOperations name="getExclusions">
        <eGenericType eClassifier="ecore:EClass ../ch.elexis.core/model/types.ecore#//List">
          <eTypeArguments eClassifier="#//tarmed/TarmedExclusion"/>
        </eGenericType>
        <eParameters name="encounter" eType="ecore:EClass ../ch.elexis.core/model/model.ecore#//IEncounter"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="services" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validFrom" eType="ecore:EDataType ../ch.elexis.core/model/types.ecore#//LocalDate"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validTo" eType="ecore:EDataType ../ch.elexis.core/model/types.ecore#//LocalDate"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="law" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="limitations" upperBound="-1"
          eType="#//tarmed/TarmedLimitation" changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="extension" eType="#//tarmed/ITarmedExtension"
          changeable="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ITarmedKumulation" abstract="true"
        interface="true">
      <eOperations name="isValidKumulation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="reference" eType="ecore:EDataType ../ch.elexis.core/model/types.ecore#//LocalDate"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="slaveCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="slaveArt" eType="#//tarmed/TarmedKumulationArt"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validSide" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validFrom" eType="ecore:EDataType ../ch.elexis.core/model/types.ecore#//LocalDate"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validTo" eType="ecore:EDataType ../ch.elexis.core/model/types.ecore#//LocalDate"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="law" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="masterCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="masterArt" eType="#//tarmed/TarmedKumulationArt"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="typ" eType="#//tarmed/TarmedKumulationTyp"
          changeable="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="TarmedLimitation" instanceClassName="ch.elexis.base.ch.arzttarife.tarmed.model.TarmedLimitation"/>
    <eClassifiers xsi:type="ecore:EDataType" name="TarmedExclusion" instanceClassName="ch.elexis.base.ch.arzttarife.tarmed.model.TarmedExclusion"/>
    <eClassifiers xsi:type="ecore:EEnum" name="MandantType">
      <eLiterals name="SPECIALIST"/>
      <eLiterals name="PRACTITIONER" value="1"/>
      <eLiterals name="TARPSYAPPRENTICE" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="TarmedKumulationArt" instanceClassName="ch.elexis.base.ch.arzttarife.tarmed.TarmedKumulationArt"/>
    <eClassifiers xsi:type="ecore:EDataType" name="TarmedKumulationTyp" instanceClassName="ch.elexis.base.ch.arzttarife.tarmed.TarmedKumulationTyp"/>
  </eSubpackages>
  <eSubpackages name="physio" nsURI="http://ch.elexis.base/model/arzttarife/physio"
      nsPrefix="ch.elexis.arzttarife.ch.physio.model">
    <eClassifiers xsi:type="ecore:EClass" name="IPhysioLeistung" abstract="true" interface="true"
        eSuperTypes="../ch.elexis.core/model/model.ecore#//IBillable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validFrom" eType="ecore:EDataType ../ch.elexis.core/model/types.ecore#//LocalDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validTo" eType="ecore:EDataType ../ch.elexis.core/model/types.ecore#//LocalDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="TP" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ziffer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="law" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="complementary" nsURI="http://ch.elexis.base/model/arzttarife/complementary"
      nsPrefix="ch.elexis.arzttarife.ch.complementary.model">
    <eClassifiers xsi:type="ecore:EClass" name="IComplementaryLeistung" abstract="true"
        interface="true" eSuperTypes="../ch.elexis.core/model/model.ecore#//IBillable ../ch.elexis.core/model/model.ecore#//Deleteable ../ch.elexis.core/model/model.ecore#//WithAssignableId">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="chapter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fixedValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fixedValueSet" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validFrom" eType="ecore:EDataType ../ch.elexis.core/model/types.ecore#//LocalDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validTo" eType="ecore:EDataType ../ch.elexis.core/model/types.ecore#//LocalDate"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="rfe" nsURI="http://ch.elexis.base/model/arzttarife/rfe" nsPrefix="ch.elexis.arzttarife.ch.tarmed.model">
    <eClassifiers xsi:type="ecore:EClass" name="IReasonForEncounter" abstract="true"
        interface="true" eSuperTypes="../ch.elexis.core/model/model.ecore#//Deleteable ../ch.elexis.core/model/model.ecore#//Identifiable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="encounter" eType="ecore:EClass ../ch.elexis.core/model/model.ecore#//IEncounter"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="pandemie" nsURI="http://ch.elexis.base/model/arzttarife/pandemie"
      nsPrefix="ch.elexis.arzttarife.ch.tarmed.model">
    <eClassifiers xsi:type="ecore:EClass" name="IPandemieLeistung" abstract="true"
        interface="true" eSuperTypes="../ch.elexis.core/model/model.ecore#//WithAssignableId ../ch.elexis.core/model/model.ecore#//IBillable ../ch.elexis.core/model/model.ecore#//Deleteable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="chapter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="cents" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validFrom" eType="ecore:EDataType ../ch.elexis.core/model/types.ecore#//LocalDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validTo" eType="ecore:EDataType ../ch.elexis.core/model/types.ecore#//LocalDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="taxpoints" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="tarmedallowance" nsURI="http://ch.elexis.base/model/arzttarife/tarmedallowance"
      nsPrefix="ch.elexis.arzttarife.ch.tarmed.model">
    <eClassifiers xsi:type="ecore:EClass" name="ITarmedAllowance" abstract="true"
        interface="true" eSuperTypes="../ch.elexis.core/model/model.ecore#//IBillable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validFrom" eType="ecore:EDataType ../ch.elexis.core/model/types.ecore#//LocalDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validTo" eType="ecore:EDataType ../ch.elexis.core/model/types.ecore#//LocalDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="chapter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="TP" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="nutrition" nsURI="http://ch.elexis.base/model/arzttarife/nutrition"
      nsPrefix="ch.elexis.arzttarife.ch.tarmed.model">
    <eClassifiers xsi:type="ecore:EClass" name="INutritionLeistung" abstract="true"
        interface="true" eSuperTypes="../ch.elexis.core/model/model.ecore#//IBillable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validFrom" eType="ecore:EDataType ../ch.elexis.core/model/types.ecore#//LocalDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validTo" eType="ecore:EDataType ../ch.elexis.core/model/types.ecore#//LocalDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="TP" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="psycho" nsURI="http://ch.elexis.base/model/arzttarife/psycho"
      nsPrefix="ch.elexis.arzttarife.ch.tarmed.model">
    <eClassifiers xsi:type="ecore:EClass" name="IPsychoLeistung" abstract="true" interface="true"
        eSuperTypes="../ch.elexis.core/model/model.ecore#//IBillable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validFrom" eType="ecore:EDataType ../ch.elexis.core/model/types.ecore#//LocalDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validTo" eType="ecore:EDataType ../ch.elexis.core/model/types.ecore#//LocalDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="TP" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="limitations" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="exclusions" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="occupational" nsURI="http://ch.elexis.base/model/arzttarife/occupational"
      nsPrefix="ch.elexis.arzttarife.ch.tarmed.model">
    <eClassifiers xsi:type="ecore:EClass" name="IOccupationalLeistung" abstract="true"
        interface="true" eSuperTypes="../ch.elexis.core/model/model.ecore#//IBillable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validFrom" eType="ecore:EDataType ../ch.elexis.core/model/types.ecore#//LocalDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validTo" eType="ecore:EDataType ../ch.elexis.core/model/types.ecore#//LocalDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="TP" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="tardoc" nsURI="http://ch.elexis.base/model/arzttarife/tardoc"
      nsPrefix="ch.elexis.arzttarife.ch.tarmed.model">
    <eClassifiers xsi:type="ecore:EClass" name="ITardocLeistung" abstract="true" interface="true"
        eSuperTypes="../ch.elexis.core/model/model.ecore#//IService">
      <eOperations name="getServiceGroups" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eParameters name="date" eType="ecore:EDataType ../ch.elexis.core/model/types.ecore#//LocalDate"/>
      </eOperations>
      <eOperations name="getServiceBlocks" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eParameters name="date" eType="ecore:EDataType ../ch.elexis.core/model/types.ecore#//LocalDate"/>
      </eOperations>
      <eOperations name="requiresSide" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="getAL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
        <eParameters name="mandator" eType="ecore:EClass ../ch.elexis.core/model/model.ecore#//IMandator"/>
      </eOperations>
      <eOperations name="getKumulations">
        <eGenericType eClassifier="ecore:EClass ../ch.elexis.core/model/types.ecore#//List">
          <eTypeArguments eClassifier="#//tardoc/ITardocKumulation"/>
        </eGenericType>
        <eParameters name="type" eType="#//tardoc/TardocKumulationArt"/>
      </eOperations>
      <eOperations name="getHierarchy">
        <eGenericType eClassifier="ecore:EClass ../ch.elexis.core/model/types.ecore#//List">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eGenericType>
        <eParameters name="date" eType="ecore:EDataType ../ch.elexis.core/model/types.ecore#//LocalDate"/>
      </eOperations>
      <eOperations name="isZuschlagsleistung" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="AL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="IPL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="digniQuali" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="digniQuanti" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="exclusion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="extension" eType="#//tardoc/ITardocExtension"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//tardoc/ITardocLeistung"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validFrom" eType="ecore:EDataType ../ch.elexis.core/model/types.ecore#//LocalDate"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validTo" eType="ecore:EDataType ../ch.elexis.core/model/types.ecore#//LocalDate"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="serviceTyp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="law" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sparte" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="chapter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nickname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ITardocExtension" abstract="true"
        interface="true" eSuperTypes="../ch.elexis.core/model/model.ecore#//Identifiable ../ch.elexis.core/model/model.ecore#//Deleteable ../ch.elexis.core/model/model.ecore#//WithExtInfo">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="limits" changeable="false"
          transient="true">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        </eGenericType>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="medInterpretation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="techInterpretation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ITardocGroup" abstract="true" interface="true"
        eSuperTypes="../ch.elexis.core/model/model.ecore#//Deleteable ../ch.elexis.core/model/model.ecore#//Identifiable">
      <eOperations name="validAt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="reference" eType="ecore:EDataType ../ch.elexis.core/model/types.ecore#//LocalDate"/>
      </eOperations>
      <eOperations name="getExclusions">
        <eGenericType eClassifier="ecore:EClass ../ch.elexis.core/model/types.ecore#//List">
          <eTypeArguments eClassifier="#//tardoc/TardocExclusion"/>
        </eGenericType>
        <eParameters name="encounter" eType="ecore:EClass ../ch.elexis.core/model/model.ecore#//IEncounter"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="services" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validFrom" eType="ecore:EDataType ../ch.elexis.core/model/types.ecore#//LocalDate"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validTo" eType="ecore:EDataType ../ch.elexis.core/model/types.ecore#//LocalDate"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="law" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="limitations" upperBound="-1"
          eType="#//tardoc/TardocLimitation" changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="extension" eType="#//tardoc/ITardocExtension"
          changeable="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ITardocKumulation" abstract="true"
        interface="true">
      <eOperations name="isValidKumulation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="reference" eType="ecore:EDataType ../ch.elexis.core/model/types.ecore#//LocalDate"/>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="slaveCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="slaveArt" eType="#//tardoc/TardocKumulationArt"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validSide" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validFrom" eType="ecore:EDataType ../ch.elexis.core/model/types.ecore#//LocalDate"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="validTo" eType="ecore:EDataType ../ch.elexis.core/model/types.ecore#//LocalDate"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="law" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="masterCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="masterArt" eType="#//tardoc/TardocKumulationArt"
          changeable="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="typ" eType="#//tardoc/TardocKumulationTyp"
          changeable="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="TardocLimitation" instanceClassName="ch.elexis.base.ch.arzttarife.tardoc.model.TardocLimitation"/>
    <eClassifiers xsi:type="ecore:EDataType" name="TardocExclusion" instanceClassName="ch.elexis.base.ch.arzttarife.tardoc.model.TardocExclusion"/>
    <eClassifiers xsi:type="ecore:EEnum" name="MandantType">
      <eLiterals name="SPECIALIST"/>
      <eLiterals name="PRACTITIONER" value="1"/>
      <eLiterals name="TARPSYAPPRENTICE" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="TardocKumulationArt" instanceClassName="ch.elexis.base.ch.arzttarife.tardoc.TardocKumulationArt"/>
    <eClassifiers xsi:type="ecore:EDataType" name="TardocKumulationTyp" instanceClassName="ch.elexis.base.ch.arzttarife.tardoc.TardocKumulationTyp"/>
  </eSubpackages>
</ecore:EPackage>
