<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="labortarif" nsURI="http://ch.elexis.base/model/labortarif" nsPrefix="ch.elexis.base.ch.labortarif.model">
  <eClassifiers xsi:type="ecore:EClass" name="ILaborLeistung" abstract="true" interface="true"
      eSuperTypes="../../ch.elexis.core/model/model.ecore#//IBillable">
    <eOperations name="isValidOn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="date" eType="ecore:EDataType ../../ch.elexis.core/model/types.ecore#//LocalDate"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="points" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="tp"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validFrom" eType="ecore:EDataType ../../ch.elexis.core/model/types.ecore#//LocalDate"
        changeable="false">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="gueltigVon"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validTo" eType="ecore:EDataType ../../ch.elexis.core/model/types.ecore#//LocalDate"
        changeable="false">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="gueltigBis"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="chapter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="speciality" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="fachbereich"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="limitation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false">
      <eAnnotations source="http://elexis.info/jpa/entity/attribute/mapping">
        <details key="attributeName" value="limitatio"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
