//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.31 at 10:05:04 PM CEST 
//


package at.medevit.ch.artikelstamm;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ITEM" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="GTIN">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="PHAR" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="DSCR">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="50"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="ADDSCR">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="50"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="ATC" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="7"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="COMP" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="NAME" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="101"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="GLN" minOccurs="0">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="13"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="PEXF" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *                   &lt;element name="PPUB" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *                   &lt;element name="PKG_SIZE" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="SL_ENTRY" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="IKSCAT" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="A"/>
 *                         &lt;enumeration value="B"/>
 *                         &lt;enumeration value="C"/>
 *                         &lt;enumeration value="D"/>
 *                         &lt;enumeration value="E"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="LIMITATION" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="LIMITATION_PTS" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="LIMITATION_TEXT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="GENERIC_TYPE" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="O"/>
 *                         &lt;enumeration value="G"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="HAS_GENERIC" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="LPPV" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="DEDUCTIBLE" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="NARCOTIC" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element name="NARCOTIC_CAS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="CREATION_DATETIME" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="LANG" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="MONTH" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="YEAR" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="CUMUL_VER" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="TYPE" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="P"/>
 *             &lt;enumeration value="N"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="DATA_QUALITY" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "item"
})
@XmlRootElement(name = "ARTIKELSTAMM")
public class ARTIKELSTAMM {

    @XmlElement(name = "ITEM")
    protected List<ARTIKELSTAMM.ITEM> item;
    @XmlAttribute(name = "CREATION_DATETIME", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationdatetime;
    @XmlAttribute(name = "LANG")
    protected String lang;
    @XmlAttribute(name = "MONTH")
    protected Integer month;
    @XmlAttribute(name = "YEAR")
    protected Integer year;
    @XmlAttribute(name = "CUMUL_VER", required = true)
    protected int cumulver;
    @XmlAttribute(name = "TYPE", required = true)
    protected String type;
    @XmlAttribute(name = "DATA_QUALITY")
    protected Integer dataquality;

    /**
     * Gets the value of the item property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the item property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getITEM().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ARTIKELSTAMM.ITEM }
     * 
     * 
     */
    public List<ARTIKELSTAMM.ITEM> getITEM() {
        if (item == null) {
            item = new ArrayList<ARTIKELSTAMM.ITEM>();
        }
        return this.item;
    }

    /**
     * Gets the value of the creationdatetime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCREATIONDATETIME() {
        return creationdatetime;
    }

    /**
     * Sets the value of the creationdatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCREATIONDATETIME(XMLGregorianCalendar value) {
        this.creationdatetime = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLANG() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLANG(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the month property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMONTH() {
        return month;
    }

    /**
     * Sets the value of the month property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMONTH(Integer value) {
        this.month = value;
    }

    /**
     * Gets the value of the year property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getYEAR() {
        return year;
    }

    /**
     * Sets the value of the year property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setYEAR(Integer value) {
        this.year = value;
    }

    /**
     * Gets the value of the cumulver property.
     * 
     */
    public int getCUMULVER() {
        return cumulver;
    }

    /**
     * Sets the value of the cumulver property.
     * 
     */
    public void setCUMULVER(int value) {
        this.cumulver = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTYPE() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTYPE(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the dataquality property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDATAQUALITY() {
        return dataquality;
    }

    /**
     * Sets the value of the dataquality property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDATAQUALITY(Integer value) {
        this.dataquality = value;
    }


    /**
     * 
     *     						Packungsgröße verrechnet, also Anzahl der
     *     						beinhalteten Elemente (bspw. 100 Tabletten)
     *     					
     * 
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="GTIN">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="PHAR" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="DSCR">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="50"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="ADDSCR">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="50"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="ATC" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="7"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="COMP" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="NAME" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="101"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="GLN" minOccurs="0">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="13"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="PEXF" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
     *         &lt;element name="PPUB" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
     *         &lt;element name="PKG_SIZE" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="SL_ENTRY" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="IKSCAT" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="A"/>
     *               &lt;enumeration value="B"/>
     *               &lt;enumeration value="C"/>
     *               &lt;enumeration value="D"/>
     *               &lt;enumeration value="E"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="LIMITATION" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="LIMITATION_PTS" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="LIMITATION_TEXT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="GENERIC_TYPE" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="O"/>
     *               &lt;enumeration value="G"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="HAS_GENERIC" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="LPPV" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="DEDUCTIBLE" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="NARCOTIC" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element name="NARCOTIC_CAS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "gtin",
        "phar",
        "dscr",
        "addscr",
        "atc",
        "comp",
        "pexf",
        "ppub",
        "pkgsize",
        "slentry",
        "ikscat",
        "limitation",
        "limitationpts",
        "limitationtext",
        "generictype",
        "hasgeneric",
        "lppv",
        "deductible",
        "narcotic",
        "narcoticcas"
    })
    public static class ITEM {

        @XmlElement(name = "GTIN", required = true)
        protected String gtin;
        @XmlElement(name = "PHAR")
        protected BigInteger phar;
        @XmlElement(name = "DSCR", required = true)
        protected String dscr;
        @XmlElement(name = "ADDSCR", required = true)
        protected String addscr;
        @XmlElement(name = "ATC")
        protected String atc;
        @XmlElement(name = "COMP")
        protected ARTIKELSTAMM.ITEM.COMP comp;
        @XmlElement(name = "PEXF")
        protected Double pexf;
        @XmlElement(name = "PPUB")
        protected Double ppub;
        @XmlElement(name = "PKG_SIZE")
        protected Integer pkgsize;
        @XmlElement(name = "SL_ENTRY")
        protected Boolean slentry;
        @XmlElement(name = "IKSCAT")
        protected String ikscat;
        @XmlElement(name = "LIMITATION")
        protected Boolean limitation;
        @XmlElement(name = "LIMITATION_PTS")
        protected Integer limitationpts;
        @XmlElement(name = "LIMITATION_TEXT")
        protected String limitationtext;
        @XmlElement(name = "GENERIC_TYPE")
        protected String generictype;
        @XmlElement(name = "HAS_GENERIC")
        protected Boolean hasgeneric;
        @XmlElement(name = "LPPV")
        protected Boolean lppv;
        @XmlElement(name = "DEDUCTIBLE")
        protected Integer deductible;
        @XmlElement(name = "NARCOTIC")
        protected Boolean narcotic;
        @XmlElement(name = "NARCOTIC_CAS")
        protected String narcoticcas;

        /**
         * Gets the value of the gtin property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGTIN() {
            return gtin;
        }

        /**
         * Sets the value of the gtin property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGTIN(String value) {
            this.gtin = value;
        }

        /**
         * Gets the value of the phar property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getPHAR() {
            return phar;
        }

        /**
         * Sets the value of the phar property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setPHAR(BigInteger value) {
            this.phar = value;
        }

        /**
         * Gets the value of the dscr property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDSCR() {
            return dscr;
        }

        /**
         * Sets the value of the dscr property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDSCR(String value) {
            this.dscr = value;
        }

        /**
         * Gets the value of the addscr property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getADDSCR() {
            return addscr;
        }

        /**
         * Sets the value of the addscr property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setADDSCR(String value) {
            this.addscr = value;
        }

        /**
         * Gets the value of the atc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getATC() {
            return atc;
        }

        /**
         * Sets the value of the atc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setATC(String value) {
            this.atc = value;
        }

        /**
         * Gets the value of the comp property.
         * 
         * @return
         *     possible object is
         *     {@link ARTIKELSTAMM.ITEM.COMP }
         *     
         */
        public ARTIKELSTAMM.ITEM.COMP getCOMP() {
            return comp;
        }

        /**
         * Sets the value of the comp property.
         * 
         * @param value
         *     allowed object is
         *     {@link ARTIKELSTAMM.ITEM.COMP }
         *     
         */
        public void setCOMP(ARTIKELSTAMM.ITEM.COMP value) {
            this.comp = value;
        }

        /**
         * Gets the value of the pexf property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getPEXF() {
            return pexf;
        }

        /**
         * Sets the value of the pexf property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setPEXF(Double value) {
            this.pexf = value;
        }

        /**
         * Gets the value of the ppub property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getPPUB() {
            return ppub;
        }

        /**
         * Sets the value of the ppub property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setPPUB(Double value) {
            this.ppub = value;
        }

        /**
         * Gets the value of the pkgsize property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getPKGSIZE() {
            return pkgsize;
        }

        /**
         * Sets the value of the pkgsize property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setPKGSIZE(Integer value) {
            this.pkgsize = value;
        }

        /**
         * Gets the value of the slentry property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isSLENTRY() {
            return slentry;
        }

        /**
         * Sets the value of the slentry property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setSLENTRY(Boolean value) {
            this.slentry = value;
        }

        /**
         * Gets the value of the ikscat property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIKSCAT() {
            return ikscat;
        }

        /**
         * Sets the value of the ikscat property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIKSCAT(String value) {
            this.ikscat = value;
        }

        /**
         * Gets the value of the limitation property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isLIMITATION() {
            return limitation;
        }

        /**
         * Sets the value of the limitation property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setLIMITATION(Boolean value) {
            this.limitation = value;
        }

        /**
         * Gets the value of the limitationpts property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getLIMITATIONPTS() {
            return limitationpts;
        }

        /**
         * Sets the value of the limitationpts property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setLIMITATIONPTS(Integer value) {
            this.limitationpts = value;
        }

        /**
         * Gets the value of the limitationtext property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLIMITATIONTEXT() {
            return limitationtext;
        }

        /**
         * Sets the value of the limitationtext property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLIMITATIONTEXT(String value) {
            this.limitationtext = value;
        }

        /**
         * Gets the value of the generictype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGENERICTYPE() {
            return generictype;
        }

        /**
         * Sets the value of the generictype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGENERICTYPE(String value) {
            this.generictype = value;
        }

        /**
         * Gets the value of the hasgeneric property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isHASGENERIC() {
            return hasgeneric;
        }

        /**
         * Sets the value of the hasgeneric property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setHASGENERIC(Boolean value) {
            this.hasgeneric = value;
        }

        /**
         * Gets the value of the lppv property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isLPPV() {
            return lppv;
        }

        /**
         * Sets the value of the lppv property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setLPPV(Boolean value) {
            this.lppv = value;
        }

        /**
         * Gets the value of the deductible property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getDEDUCTIBLE() {
            return deductible;
        }

        /**
         * Sets the value of the deductible property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setDEDUCTIBLE(Integer value) {
            this.deductible = value;
        }

        /**
         * Gets the value of the narcotic property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isNARCOTIC() {
            return narcotic;
        }

        /**
         * Sets the value of the narcotic property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setNARCOTIC(Boolean value) {
            this.narcotic = value;
        }

        /**
         * Gets the value of the narcoticcas property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNARCOTICCAS() {
            return narcoticcas;
        }

        /**
         * Sets the value of the narcoticcas property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNARCOTICCAS(String value) {
            this.narcoticcas = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="NAME" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="101"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="GLN" minOccurs="0">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="13"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "gln"
        })
        public static class COMP {

            @XmlElement(name = "NAME")
            protected String name;
            @XmlElement(name = "GLN")
            protected String gln;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNAME() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNAME(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the gln property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGLN() {
                return gln;
            }

            /**
             * Sets the value of the gln property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGLN(String value) {
                this.gln = value;
            }

        }

    }

}
