# This workflow will build the Eclipse RCP application with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set locale de_CH.UTF-8
      run: |
          sudo locale-gen de_CH.UTF-8
          sudo update-locale LANG=de_CH.UTF-8
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'
    - name: Install xvfb
      run: sudo apt-get install xvfb
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      run: |
            HTTP_STATUS=`curl -LI https://download.elexis.info/elexis/${GITHUB_REF##*/}/p2/elexis-3-core/p2.index -o /dev/null -w '%{http_code}\n' -s`
            echo for branch ${GITHUB_REF##*/} the HTTP_STATUS was ${HTTP_STATUS}
            if [ "${HTTP_STATUS}" == "200" ]; then
              echo Using ${GITHUB_REF##*/}
              export BRANCH=${GITHUB_REF##*/}
            else
              export BRANCH=master
              echo bad branch name. Trying master
            fi
            xvfb-run mvn -V clean verify -Dgit.target.branch=${BRANCH} -Dgit.core.branch=${BRANCH}
      env:
        LC_ALL: de_CH.UTF-8
        LANG: en_US.UTF-8
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
       files: ./tests/**/target/surefire-reports/TEST-*.xml
